
SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_MENU;

SELECT * FROM SY_MENU;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM02';


SELECT * FROM SY_CMMN_CODE;

SELECT * FROM SY_SYS_MANAGE;

SELECT * FROM PM_PRJCT_MENU;

SELECT
	PRJCT_SEQNO VALUE
  ,PRJCT_NM KEY
FROM PM_PRJCT;


SELECT * FROM SY_USER;

SELECT * FROM SY_INSPCT_INSTT;


SELECT
	INSPCT_INSTT_SEQNO VALUE
  ,INSPCT_INSTT_NM KEY
FROM SY_INSPCT_INSTT
WHERE PRJCT_MANAGE_DEPT_AT = 'N'
;

UPDATE SY_INSPCT_INSTT SET
PRJCT_MANAGE_DEPT_AT = 'Y'
WHERE INSPCT_INSTT_SEQNO IN ( 48
,49
,50
,51
,52
,53);

COMMIT;

SELECT * FROM PM_PRJCT;

SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM PM_PRJCT_MENU;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM02';


INSERT INTO PM_PRJCT_MENU VALUES
(
		SQ_PM_PRJCT_MENU.NEXTVAL
  	, 1
    , 1
    , 1
    , '공통'
    , '시스템관리'
    , 'master'
    , 'CmmnCodeM'
    , '22-06-23'
    , '22-06-23'
    , 'N'
    , 'N'
    , '비고'
    , 'Y'
    , 'N'
    , 1
    , SYSDATE
);

UPDATE PM_PRJCT_MENU SET
MENU_SE_CODE = 'PM02000001';

COMMIT;

SELECT USER_NM FROM SY_USER WHERE USER_ID = 1;


SELECT
	A.PRJCT_MENU_SEQNO
  , A.UPPER_PRJCT_MENU_SEQNO
  , A.PRJCT_SEQNO
  ,	A.CHARGER_ID
  , A.MENU_NM
  , A.MENU_ID
  , (SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE UPPER_CMMN_CODE = 'PM02' AND CMMN_CODE = A.MENU_SE_CODE) menuSeCodeNm
  , (SELECT USER_NM FROM SY_USER WHERE USER_ID = A.CHARGER_ID) changerNm
  , A.FILE_NM
  , A.RM
  , A.USE_AT
FROM PM_PRJCT_MENU A
INNER JOIN PM_PRJCT B ON A.PRJCT_SEQNO = B.PRJCT_SEQNO
WHERE A.USE_AT = 'Y'
	AND A.DELETE_AT = 'N'
  AND A.PRJCT_SEQNO = 1
  AND B.USE_AT = 'Y'
  AND B.DELETE_AT = 'N'
START WITH A.UPPER_PRJCT_MENU_SEQNO IS NULL
CONNECT BY PRIOR A.PRJCT_MENU_SEQNO = A.UPPER_PRJCT_MENU_SEQNO;

SELECT * FROM PM_PRJCT_MENU
WHERE PRJCT_SEQNO = 1;

SELECT * FROM PM_PRJCT_MENU;

SELECT * FROM SY_CMMN_CODE;

SELECT * FROM PM_UNIT_TEST;


