
SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT * FROM SY_INSPCT_INSTT
START WITH UPPER_INSPCT_INSTT_SEQNO IS NULL
CONNECT BY PRIOR INSPCT_INSTT_SEQNO = UPPER_INSPCT_INSTT_SEQNO
ORDER SIBLINGS BY UPPER_INSPCT_INSTT_SEQNO;

SELECT * FROM SY_USER
WHERE DELETE_AT = 'N';

SELECT * FROM SY_AUTHOR_USER;

SELECT * FROM SY_INSPCT_INSTT;

SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT * FROM
(SELECT * FROM SY_INSPCT_INSTT
START WITH UPPER_INSPCT_INSTT_SEQNO IS NULL
CONNECT BY PRIOR INSPCT_INSTT_SEQNO = UPPER_INSPCT_INSTT_SEQNO
ORDER SIBLINGS BY UPPER_INSPCT_INSTT_SEQNO) A
LEFT JOIN SY_INSPCT_INSTT_USER B ON A.INSPCT_INSTT_SEQNO = B.INSPCT_INSTT_SEQNO
LEFT JOIN SY_USER C ON B.USER_ID = C.USER_ID;


SELECT CASE
      WHEN LEVEL <= 1 THEN INSPCT_INSTT_NM
				ELSE LPAD(' ' ,2*(LEVEL-1), ' ') || 'L' || INSPCT_INSTT_NM
        END AS KEY
        ,	INSPCT_INSTT_SEQNO AS VALUE
FROM SY_INSPCT_INSTT
WHERE DELETE_AT = 'N'
    START WITH      UPPER_INSPCT_INSTT_SEQNO IS NULL
CONNECT BY PRIOR    INSPCT_INSTT_SEQNO = UPPER_INSPCT_INSTT_SEQNO
ORDER SIBLINGS BY   INSPCT_INSTT_NM;



SELECT * FROM SY_INSPCT_INSTT;


SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT * FROM SY_USER
WHERE USER_NM = '관리자1';


SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_USER;

SELECT * FROM SY_INSPCT_INSTT_USER;
SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_INSPCT_INSTT_USER;

INSERT INTO SY_INSPCT_INSTT_USER
VALUES (
	23426,
	1,
  SYSDATE,
  null
);


SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT;

UPDATE SY_USER SET
DELETE_AT = 'Y'
WHERE GW_EMPLYR_INTRFC_KEY IS NOT NULL;

UPDATE SY_INSPCT_INSTT SET
DELETE_AT = 'Y'
WHERE GW_ORGNZT_INTRFC_KEY IS NOT NULL;

ROLLBACK;

SELECT * FROM SY_INSPCT_INSTT
WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL;


SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_INSPCT_INSTT
WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL
AND USE_AT = 'N';

SELECT SQ_SY_INSPCT_INSTT.NEXTVAL FROM DUAL;

SELECT INSPCT_INSTT_SEQNO FROM SY_INSPCT_INSTT
WHERE GW_ORGNZT_INTRFC_KEY = '23426';


SELECT * FROM SY_USER;

SELECT SQ_SY_USER.NEXTVAL FROM DUAL;


DELETE FROM SY_INSPCT_INSTT;

DELETE FROM SY_INSPCT_INSTT_USER;

SELECT * FROM SY_USER;

DELETE FROM SY_USER
WHERE GW_EMPLYR_INTRFC_KEY IS NOT NULL;

COMMIT;

SELECT COUNT(INSPCT_INSTT_SEQNO), NVL(INSPCT_INSTT_SEQNO, 10) FROM SY_INSPCT_INSTT
WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL;

SELECT
	CASE COUNT(INSPCT_INSTT_SEQNO)
  	WHEN 0 THEN 20
    ELSE (SELECT MIN(INSPCT_INSTT_SEQNO) FROM SY_INSPCT_INSTT WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL GROUP BY INSPCT_INSTT_SEQNO)
	END
FROM SY_INSPCT_INSTT
WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL;


SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT NULL FROM DUAL;
SELECT 10 FROM DUAL;
SELECT SQ_SY_INSPCT_INSTT.NEXTVAL FROM DUAL;


SELECT INSPCT_INSTT_SEQNO
FROM SY_INSPCT_INSTT
WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL;


SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_USER;

SELECT INSPCT_INSTT_SEQNO FROM SY_INSPCT_INSTT
WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL;

SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT SQ_SY_INSPCT_INSTT.NEXTVAL FROM DUAL;
SELECT SQ_SY_USER.NEXTVAL FROM DUAL;

SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_USER
ORDER BY USER_ID DESC;


SELECT USER_ID FROM SY_USER
WHERE GW_EMPLYR_INTRFC_KEY = 5656722;

SELECT INSPCT_INSTT_SEQNO FROM SY_INSPCT_INSTT
WHERE GW_ORGNZT_INTRFC_KEY = 23406;

SELECT * FROM SY_INSPCT_INSTT;


SELECT COUNT(*) FROM  SY_INSPCT_INSTT
WHERE UPPER_INSPCT_INSTT_SEQNO IS NULL;

SELECT * FROM SY_USER
WHERE USER_NM = '최상용'
ORDER BY USER_ID DESC;

SELECT * FROM SY_INSPCT_INSTT
ORDER BY INSPCT_INSTT_SEQNO DESC;

SELECT * FROM SY_INSPCT_INSTT_USER
ORDER BY INSPCT_INSTT_SEQNO DESC;

SELECT * FROM SY_USER
ORDER BY USER_ID DESC;






