SELECT A.ATCHMNFL_SEQNO FROM RS_PCN A;

SELECT * FROM SY_ATCHMNFL;
SELECT * FROM SY_ATCHMNFL_DETAIL;

SELECT A.PCN_SEQNO, C.* FROM RS_PCN A
JOIN SY_ATCHMNFL B ON A.ATCHMNFL_SEQNO = B.ATCHMNFL_SEQNO
JOIN SY_ATCHMNFL_DETAIL C ON A.ATCHMNFL_SEQNO = C.ATCHMNFL_SEQNO;


SELECT * FROM SY_MENU
WHERE USE_AT = 'Y'
AND MNL_USE_AT = 'Y'
START WITH UPPER_MENU_SEQNO IS NULL
CONNECT BY PRIOR MENU_SEQNO = UPPER_MENU_SEQNO
ORDER SIBLINGS BY SORT_ORDR;



SELECT * FROM SY_MENU
ORDER BY MENU_SEQNO DESC;

SELECT * FROM SY_LANG_CMMN_CODE;
SELECT * FROM SY_LANG_MENU
ORDER BY LANG_MENU_SEQNO DESC;
SELECT * FROM SY_LANG_MASTR
ORDER BY LANG_MASTR_SEQNO DESC;
SELECT * FROM SY_LANG_DETAIL
ORDER BY LANG_DETAIL_SEQNO DESC;



