SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

SELECT * FROM PM_UNIT_TEST
WHERE UNIT_TEST_SEQNO = 142;

SELECT * FROM PM_UNIT_TEST;


SELECT * FROM PM_PRJCT_CHARGER;

SELECT *
FROM PM_UNIT_TEST A
INNER JOIN PM_PRJCT_MENU B ON A.PRJCT_MENU_SEQNO = B.PRJCT_MENU_SEQNO
INNER JOIN PM_PRJCT C ON B.PRJCT_SEQNO = C.PRJCT_SEQNO
WHERE A.TESTER_ID IN (SELECT CHARGER_ID FROM PM_PRJCT_CHARGER WHERE PRJCT_SEQNO = C.PRJCT_SEQNO);

SELECT * FROM PM_UNIT_TEST
ORDER BY UNIT_TEST_SEQNO DESC;

UPDATE PM_UNIT_TEST SET
TESTER_ID = 151
WHERE UNIT_TEST_SEQNO > 130;

COMMIT;

SELECT * FROM SY_USER
WHERE USER_NM = '우재의';

SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

SELECT * FROM SY_USER;

SELECT
			    	MENU.MENU_SEQNO,
			   		MENU.UPPER_MENU_SEQNO,
					MENU.MENU_NM,
			    	MENU.MENU_DC,
			   		MENU.MNL_CN,
			    	(SELECT X.MENU_URL
			              FROM    SY_MENU X
			              JOIN
			              (
				              SELECT
					            DISTINCT SA.MENU_SEQNO, MIN(SA.SORT_ORDR) OVER(PARTITION BY SA.UPPER_MENU_SEQNO ORDER BY SA.UPPER_MENU_SEQNO, SA.SORT_ORDR) AS SORT_ORDR
					          FROM SY_MENU SA
					          WHERE SA.USE_AT = 'Y'
					          AND SA.UPPER_MENU_SEQNO IS NOT NULL
					          START WITH SA.MENU_SEQNO IN (
			                      SELECT MENU_SEQNO
			                         FROM SY_AUTHOR_MENU
			                        WHERE AUTHOR_CODE IN (
				                        SELECT
											A.AUTHOR_CODE
										FROM SY_AUTHOR_USER A
										WHERE A.USER_ID IN (
											SELECT TO_NUMBER( '1' /**P*/) FROM DUAL
										)
 									)
 								)
          						CONNECT BY  SA.MENU_SEQNO = PRIOR SA.UPPER_MENU_SEQNO
 							) AA
			                   ON X.MENU_SEQNO = AA.MENU_SEQNO AND X.SORT_ORDR = AA.SORT_ORDR
			             WHERE CONNECT_BY_ISLEAF = 1 AND ROWNUM = 1
			        CONNECT BY PRIOR X.MENU_SEQNO = X.UPPER_MENU_SEQNO
			        START WITH X.UPPER_MENU_SEQNO = MENU.MENU_SEQNO)
			          AS MENU_URL,
			       (    SELECT X.MENU_SEQNO
			              FROM    SY_MENU X
			              JOIN
			              (
				              SELECT
					            DISTINCT SA.MENU_SEQNO, MIN(SA.SORT_ORDR) OVER(PARTITION BY SA.UPPER_MENU_SEQNO ORDER BY SA.UPPER_MENU_SEQNO, SA.SORT_ORDR) AS SORT_ORDR
					          FROM SY_MENU SA
					          WHERE SA.USE_AT = 'Y'
					          AND SA.UPPER_MENU_SEQNO IS NOT NULL
					          START WITH SA.MENU_SEQNO IN (
			                      SELECT MENU_SEQNO
			                         FROM SY_AUTHOR_MENU
			                        WHERE AUTHOR_CODE IN (
				                        SELECT
											A.AUTHOR_CODE
										FROM SY_AUTHOR_USER A
										WHERE A.USER_ID IN (
											SELECT TO_NUMBER( '1' /**P*/) FROM DUAL
										)
 									)
 								)
          						CONNECT BY  SA.MENU_SEQNO = PRIOR SA.UPPER_MENU_SEQNO
 							) AA
			                   ON X.MENU_SEQNO = AA.MENU_SEQNO AND X.SORT_ORDR = AA.SORT_ORDR
			             WHERE CONNECT_BY_ISLEAF = 1 AND ROWNUM = 1
			        CONNECT BY PRIOR X.MENU_SEQNO = X.UPPER_MENU_SEQNO
			        START WITH X.UPPER_MENU_SEQNO = MENU.MENU_SEQNO)
			          AS MENU_CHILD_SEQNO,
			       MENU.SORT_ORDR,
			       MENU.USE_AT,
			       MENU.LAST_CHANGER_ID,
			       MENU.LAST_CHANGE_DT
			  FROM SY_MENU MENU

			  RIGHT OUTER JOIN
			  (
				  SELECT
				  SA.MENU_SEQNO
		          FROM SY_MENU SA
		          WHERE SA.USE_AT = 'Y'
		          AND SA.UPPER_MENU_SEQNO IS NOT NULL
		          START WITH SA.MENU_SEQNO IN (
				       	SELECT MENU_SEQNO
			            FROM SY_AUTHOR_MENU
			            WHERE AUTHOR_CODE IN (
							SELECT
								A.AUTHOR_CODE
							FROM SY_AUTHOR_USER A
							WHERE A.USER_ID IN (
								SELECT TO_NUMBER( '1' /**P*/) FROM DUAL
							)
			            )
					)
          		CONNECT BY  SA.MENU_SEQNO = PRIOR SA.UPPER_MENU_SEQNO
	            GROUP BY MENU_SEQNO
			 ) AUTHOR_MENU ON MENU.MENU_SEQNO = AUTHOR_MENU.MENU_SEQNO
			 WHERE UPPER_MENU_SEQNO IN ('1000')

			 ORDER BY MENU.SORT_ORDR;

SELECT * FROM SY_MENU;

SELECT
	SA.MENU_SEQNO
FROM SY_MENU SA
WHERE SA.USE_AT = 'Y'
AND SA.UPPER_MENU_SEQNO IS NOT NULL
START WITH SA.MENU_SEQNO IN (
	SELECT MENU_SEQNO
	FROM SY_AUTHOR_MENU
	WHERE AUTHOR_CODE IN (
		SELECT
			A.AUTHOR_CODE
		FROM SY_AUTHOR_USER A
		WHERE A.USER_ID IN (
			SELECT TO_NUMBER( '1' /**P*/) FROM DUAL
		)
	)
)
CONNECT BY SA.MENU_SEQNO = PRIOR SA.UPPER_MENU_SEQNO
GROUP BY MENU_SEQNO;

SELECT * FROM SY_AUTHOR_MENU;

SELECT MENU_SEQNO FROM SY_AUTHOR_MENU
WHERE AUTHOR_CODE IN (
	SELECT A.AUTHOR_CODE FROM SY_AUTHOR_USER A WHERE A.USER_ID = 1
);

SELECT A.AUTHOR_CODE FROM SY_AUTHOR_USER A WHERE A.USER_ID = 1;


SELECT * FROM SY_AUTHOR;

SELECT * FROM SY_AUTHOR_MENU;

SELECT * FROM SY_AUTHOR_MENU;

SELECT * FROM SY_MENU;

SELECT * FROM SY_AUTHOR_USER
WHERE USER_ID = 1;

INSERT INTO SY_AUTHOR_USER VALUES(
	1,
	1,
  'Y',
  'Y',
  'Y',
  'Y',
  1,
  SYSDATE);

COMMIT;
SELECT * FROM SY_USER
WHERE USER_NM = '관리자';


SELECT * FROM PM_PRJCT
ORDER BY PRJCT_SEQNO DESC;

SELECT * FROM SY_USER
ORDER BY USER_ID DESc;

SELECT * FROM PM_PRJCT
ORDER BY PRJCT_SEQNO DESC;

DELETE FROM PM_PRJCT
WHERE PRJCT_SEQNO >= 72;

COMMIT;


SELECT * FROM SY_ENTRPS;




