SELECT * FROM IM_RCEPT_ENTRPS A;

SELECT * FROM IM_RCEPT A
INNER JOIN IM_RCEPT_ENTRPS B ON A.RCEPT_SEQNO = B.RCEPT_SEQNO
INNER JOIN IM_RCEPT_SPLORE C ON C.RCEPT_SPLORE_SEQNO
WHERE A.RCEPT_SEQNO = 411;


SELECT * FROM IM_RCEPT_SPLORE A
LEFT JOIN IM_RCEPT B ON A.RCEPT_SEQNO = B.RCEPT_SEQNO
LEFT JOIN IM_RCEPT_ENTRPS C ON A.RCEPT_SEQNO = C.RCEPT_SEQNO AND C.ENTRPS_SE_CODE = 'IM23000001'
WHERE A.RCEPT_SPLORE_SEQNO = 1101;


SELECT * FROM SY_CMMN_CODE A
WHERE A.CMMN_CODE = 'IM23000001';


SELECT A.RPRSNTV_NM, A.RPRSNTV_ENG_NM FROM IM_RCEPT_ENTRPS A;

SELECT * FROM SY_ENTRPS A
WHERE A.ENTRPS_NM = '거래자123';


SELECT * FROM SY_ENTRPS_CHARGER A
WHERE A.ENTRPS_SEQNO = '38867';CHARGER_ENG_NM,

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'SY54';


SELECT A.MNFCTUR_NO FROM IM_RCEPT_SPLORE A;


SELECT * FROM IM_RCEPT;


SELECT A.ENG_MNFCTUR_NO FROM IM_RCEPT_ENG_INFO A;


SELECT E.REQEST_ENG_SEQNO
	       , A.RCEPT_SEQNO
	       , A.RCEPT_SPLORE_SEQNO
	       , NVL(E.PRDUCT_ENG_NM, A.PRDUCT_NM) AS PRDUCT_ENG_NM
	       , NVL(E.SPLORE_ENG_NM, A.SPLORE_NM) AS SPLORE_ENG_NM
           , NVL(E.PRDLST_ENG_NM, NVL(F.ENG_NM, A.PRDLST_NM)) AS PRDLST_ENG_NM
	       , NVL(E.IRDNT_MTRQLT_ENG_CN, NVL(E.PRDLST_ENG_NM, NVL(F.ENG_NM, A.PRDLST_NM))||NVL2(A.IRDNT_MTRQLT_CN,', '||A.IRDNT_MTRQLT_CN,A.IRDNT_MTRQLT_CN)) AS IRDNT_MTRQLT_ENG_CN
		   , NVL(E.ENTRPS_ENG_NM, NVL(C.ENTRPS_ENG_NM, C.ENTRPS_NM)) AS ENTRPS_ENG_NM
	       , NVL(E.RPRSNTV_ENG_NM, C.CHARGER_NM) AS RPRSNTV_ENG_NM
	       , NVL(E.DETAIL_ENG_ADRES ,NVL(D.ENG_ADRES, D.ADRES)) AS DETAIL_ENG_ADRES
	       , NVL(E.MNFCTUR_CMPNY_ENG_ADRES, A.MNFCTUR_CMPNY_ADRES) AS MNFCTUR_CMPNY_ENG_ADRES
	       , NVL(E.MNFCTUR_CMPNY_ENG_NM ,A.MNFCTUR_CMPNY_NM) AS MNFCTUR_CMPNY_ENG_NM
	       , NVL(E.ORGPLCE_ENG_NM, A.ORGPLCE_NM) AS ORGPLCE_ENG_NM
	       , NVL(E.INSPCT_PURPS_ENG_NM, (SELECT XA.CMMN_CODE_NM FROM SY_CMMN_CODE XA WHERE XA.CMMN_CODE = B.INSPCT_PURPS_CODE)) AS INSPCT_PURPS_ENG_NM
	       , NVL(E.ENG_TELNO, NVL(C.TELNO_ENG_NM, C.TELNO)) AS ENG_TELNO
	       , NVL(E.ENG_FXNUM, NVL(C.FXNUM_ENG_NM, C.FXNUM)) AS ENG_FXNUM
	       , NVL(E.ENG_RM, A.RM) AS ENG_RM
	       , NVL(E.VALID_TMLMT, A.DISTB_TMLMT_DTE||NVL2(A.DISTB_TMLMT_HM_VALUE,'/'||A.DISTB_TMLMT_HM_VALUE,A.DISTB_TMLMT_HM_VALUE)
				 ||NVL2(A.VALID_TMLMT,'제조일로부터 '||A.VALID_TMLMT||(SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE CMMN_CODE = A.DISTB_TMLMT_UNIT),A.VALID_TMLMT)) AS VALID_TMLMT
	       , NVL(E.ENG_MNFCTUR_NO ,A.MNFCTUR_NO) AS ENG_MNFCTUR_NO


	  FROM IM_RCEPT_SPLORE A
	  LEFT JOIN IM_RCEPT B ON B.RCEPT_SEQNO = A.RCEPT_SEQNO
	  LEFT JOIN IM_RCEPT_ENTRPS C ON C.RCEPT_SEQNO = B.RCEPT_SEQNO AND C.ENTRPS_SE_CODE = 'IM23000001'
	  LEFT JOIN SY_ENTRPS D ON D.ENTRPS_SEQNO = C.ENTRPS_SEQNO
	  LEFT JOIN IM_RCEPT_ENG_INFO E ON E.RCEPT_SPLORE_SEQNO = A.RCEPT_SPLORE_SEQNO
	  LEFT JOIN SY_PRDLST F ON F.PRDLST_SEQNO = A.PRDLST_SEQNO
	 WHERE A.RCEPT_SPLORE_SEQNO =  '995';



SELECT * FROM IM_RCEPT_SPLORE
WHERE SPLORE_RCEPT_NO = 'TT2101G0001-002';


SELECT A.ENG_MNFCTUR_NO FROM IM_RCEPT_ENG_INFO A;




SELECT * FROM IM_RCEPT_ENG_INFO;


SELECT NVL(CA.ENG_MNFCTUR_NO, A.MNFCTUR_NO) AS MNFCTUR_NO FROM IM_RCEPT_SPLORE A
LEFT JOIN IM_RCEPT_ENG_INFO CA ON A.RCEPT_SPLORE_SEQNO = CA.RCEPT_SPLORE_SEQNO;


SELECT * FROM IM_RCEPT_SPLORE
WHERE SPLORE_NM = '다크 가나슈 사블레 쿠키';




SELECT
A.RCEPT_SPLORE_SEQNO,
A.SPLORE_RCEPT_NO,
A.SPLORE_RCEPT_DTE,
A.PRDUCT_NM,
NVL(CA.ENG_MNFCTUR_NO, A.MNFCTUR_NO) AS MNFCTUR_NO,
CA.ENG_MNFCTUR_NO,
A.IRDNT_MTRQLT_CN,
A.MNFCTUR_DTE||NVL2(A.MNFCTUR_DTE_HM_VALUE,'/'||A.MNFCTUR_DTE_HM_VALUE,A.MNFCTUR_DTE_HM_VALUE) AS MNFCTUR_DTE,
A.DISTB_TMLMT_DTE||NVL2(A.DISTB_TMLMT_HM_VALUE,'/'||A.DISTB_TMLMT_HM_VALUE,A.DISTB_TMLMT_HM_VALUE)
 ||NVL2(A.VALID_TMLMT,'제조일로부터 '||A.VALID_TMLMT||(SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE CMMN_CODE = A.DISTB_TMLMT_UNIT),A.VALID_TMLMT) AS DISTB_TMLMT_DTE,
A.MNFCTUR_CMPNY_NM,
A.MNFCTUR_CMPNY_ADRES,
A.ORGPLCE_NM,
(SELECT TMPR_FIELD1_VALUE FROM SY_CMMN_CODE WHERE CMMN_CODE = A.JDGMNT_WORD_CODE) AS JDGMNT_WORD_NM,
DECODE(A.SPLORE_ATCHMNFL_SEQNO,NULL,'N','Y') AS SPLORE_ATCHMNFL_SENQNO_YN,
A.RM,
A.PRDLST_MNFCTUR_STTEMNT_NO,
CA.PRDUCT_ENG_NM,
CA.IRDNT_MTRQLT_ENG_CN,
CA.MNFCTUR_CMPNY_ENG_NM,
CA.MNFCTUR_CMPNY_ENG_ADRES,
CA.ORGPLCE_ENG_NM,
CA.ENG_RM,
CA.RPRSNTV_ENG_NM,
CA.ENTRPS_ENG_NM,
CA.INSPCT_PURPS_ENG_NM,
CA.DETAIL_ENG_ADRES,
B.INSPCT_PURPS_CODE,
C.INSPCT_INSTT_NM,
C.INSTT_ENG_NM,
CA.VALID_TMLMT,
CASE
WHEN A.PROGRS_SITTN_CODE = 'IM04000012'
THEN 'D:\\AttachFile\\fileUpload\\File'||
(SELECT STRE_FILE_NM FROM SY_ATCHMNFL_DETAIL
WHERE C.OFFCS_FILE_SEQNO = ATCHMNFL_SEQNO AND USE_AT = 'Y') ELSE '' END AS OFFCS_IMG,


D.ENTRPS_NM,
D.ENTRPS_ENG_NM,
D.CHARGER_NM,
D.ADRES,
E.ISSU_NO,
TO_CHAR(F.LAST_SANCTN_DTE,'YYYY-MM-dd') AS LAST_SANCTN_DTE,

(SELECT USER_ENG_NM FROM SY_USER WHERE USER_ID = XD.LAST_SANCTNER_ID) AS SANCTNER_NM,
'$6' AS ISSU_NO_JAVA,
'$7' AS ISSU_DTE_JAVA
FROM IM_RCEPT_SPLORE A
JOIN IM_RCEPT B
ON A.RCEPT_SEQNO = B.RCEPT_SEQNO
JOIN SY_INSPCT_INSTT C
ON B.INSPCT_INSTT_CODE = C.INSPCT_INSTT_CODE
JOIN IM_RCEPT_ENTRPS D
ON B.RCEPT_SEQNO = D.RCEPT_SEQNO
LEFT JOIN IM_ISSU E
ON A.GRDCRT_ISSU_SEQNO = E.ISSU_SEQNO
LEFT JOIN IM_RCEPT_SPLORE_VIEW F
ON A.RCEPT_SPLORE_SEQNO = F.RCEPT_SPLORE_SEQNO
LEFT JOIN IM_RCEPT_EXPR_IEM G
ON A.RCEPT_SPLORE_SEQNO = G.RCEPT_SPLORE_SEQNO
LEFT JOIN SY_USER AA
ON G.RESULT_REGISTER_ID = AA.USER_ID
LEFT JOIN IM_RCEPT_SPLORE_VIEW XD
ON A.RCEPT_SPLORE_SEQNO = XD.RCEPT_SPLORE_SEQNO


LEFT JOIN IM_RCEPT_ENG_INFO CA
ON A.RCEPT_SPLORE_SEQNO = CA.RCEPT_SPLORE_SEQNO




WHERE A.RCEPT_SPLORE_SEQNO IN (989)
AND D.ENTRPS_SE_CODE = 'IM23000001'

GROUP BY
A.RCEPT_SPLORE_SEQNO,
A.JDGMNT_WORD_CODE,
A.SPLORE_RCEPT_NO,
A.SPLORE_RCEPT_DTE,
A.PRDUCT_NM,
A.MNFCTUR_NO,
A.IRDNT_MTRQLT_CN,
A.MNFCTUR_DTE,
A.MNFCTUR_DTE_HM_VALUE,
A.VALID_TMLMT,
A.DISTB_TMLMT_DTE,
A.DISTB_TMLMT_UNIT,
A.DISTB_TMLMT_HM_VALUE,
A.MNFCTUR_CMPNY_NM,
A.MNFCTUR_CMPNY_ADRES,
A.SANCTN_SEQNO,
B.INSPCT_PURPS_CODE,
A.ORGPLCE_NM,
A.JDGMNT_VALUE,
A.RM,
A.SPLORE_ATCHMNFL_SEQNO,
C.INSPCT_INSTT_NM,
C.OFFCS_FILE_SEQNO,
D.ENTRPS_NM,
D.CHARGER_NM,
D.ADRES,
E.ISSU_NO,
F.LAST_SANCTN_DTE,
XD.LAST_SANCTNER_ID,
CA.PRDUCT_ENG_NM,
CA.IRDNT_MTRQLT_ENG_CN,
CA.MNFCTUR_CMPNY_ENG_NM,
CA.MNFCTUR_CMPNY_ENG_ADRES,
CA.ORGPLCE_ENG_NM,
CA.ENG_RM,
CA.RPRSNTV_ENG_NM,
CA.ENTRPS_ENG_NM,
CA.INSPCT_PURPS_ENG_NM,
CA.DETAIL_ENG_ADRES,
C.INSTT_ENG_NM,
D.ENTRPS_ENG_NM,
CA.RPRSNTV_ENG_NM,
CA.VALID_TMLMT,
A.PRDLST_MNFCTUR_STTEMNT_NO,
A.PROGRS_SITTN_CODE,
CA.ENG_MNFCTUR_NO
ORDER BY A.SPLORE_RCEPT_NO;


SELECT * FROM SY_PRINTNG;


SELECT * FROM IM_RCEPT_SPLORE A;
SELECT A.CHARGER_NM FROM IM_RCEPT_ENTRPS A;

SELECT * FROM IM_RCEPT_ENG_INFO;



