
SELECT * FROM PM_PRJCT_MENU;

SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_MENU;


UPDATE PM_PRJCT_MENU SET
	SORT_ORDR = 1
WHERE PRJCT_MENU_SEQNO = 2;

ROLLBACK;

SELECT * FROM SY_INSPCT_INSTT;

SELECT * FROM AT_LOGIN_HIST HIST
INNER JOIN SY_USER A ON A.USER_ID = HIST.USER_ID
INNER JOIN SY_INSPCT_INSTT_USER B ON A.USER_ID = B.USER_ID
INNER JOIN SY_INSPCT_INSTT C ON B.INSPCT_INSTT_SEQNO = C.INSPCT_INSTT_SEQNO;

SELECT * FROM AT_LOGIN_HIST;

DELETE FROM AT_LOGIN_HIST;

COMMIT;
ROLLBACK;

SELECT
			D.INSPCT_INSTT_NM,
			B.USER_NM,
			A.LOGIN_ID,
			A.LOGIN_IP,
			TO_CHAR (A.LOGIN_DT, 'YYYY-MM-DD HH24:MI:SS') LOGIN_DT,
		  TO_CHAR (A.LOGOUT_DT, 'YYYY-MM-DD HH24:MI:SS') LOGOUT_DT
		FROM AT_LOGIN_HIST A
		INNER JOIN SY_USER B ON A.USER_ID = B.USER_ID
		INNER JOIN SY_INSPCT_INSTT_USER C ON B.USER_ID = C.USER_ID
		INNER JOIN SY_INSPCT_INSTT D ON C.INSPCT_INSTT_SEQNO = D.INSPCT_INSTT_SEQNO
		WHERE 1=1;

SELECT * FROM SY_EXCP_LOG;

SELECT * FROM AT_LOGIN_HIST;

SELECT * FROM SY_BBS;
SELECT * FROM SY_BBS_ANSWER;
SELECT * FROM SY_BBS_SNTNC;

UPDATE SY_BBS SET
USER_SNTNCWRITE_AT = 'N';

COMMIT;


SELECT * FROM SY_BBS_ANSWER;

SELECT * FROM SY_BBS_SNTNC;

SELECT * FROM SY_USER
WHERE USER_NM = '¹ÚÁØ±Ô';


SELECT
			MAX(D.INSPCT_INSTT_NM),
			MAX(D.INSPCT_INSTT_SEQNO),
			MAX(D.INSPCT_INSTT_NM) inspctInsttNm,
			MAX(B.USER_NM) userNm,
			MAX(A.LOGIN_ID) loginId,
			MAX(A.LOGIN_IP) loginIp,
			TO_CHAR (A.LOGIN_DT, 'YYYY-MM-DD HH24:MI:SS') LOGIN_DT,
		  TO_CHAR (MAX(A.LOGOUT_DT), 'YYYY-MM-DD HH24:MI:SS') LOGOUT_DT
		FROM AT_LOGIN_HIST A
		INNER JOIN SY_USER B ON A.USER_ID = B.USER_ID
		LEFT JOIN SY_INSPCT_INSTT_USER C ON B.USER_ID = C.USER_ID
		LEFT JOIN SY_INSPCT_INSTT D ON C.INSPCT_INSTT_SEQNO = D.INSPCT_INSTT_SEQNO
		WHERE 1=1
	    GROUP BY A.LOGIN_DT
	    ORDER BY LOGIN_DT DESC;


SELECT * FROM AT_LOGIN_HIST;






