SELECT * FROM PM_UNIT_TEST;

SELECT
		C.PRJCT_SEQNO
		, A.UNIT_TEST_SEQNO
		, A.PRJCT_MENU_SEQNO
		, A.TESTER_ID
		, A.OPETR_ID
		, A.RERGIST_NUMOT
		, C.PRJCT_NM
		, B.MENU_NM
		, E.USER_NM chargerNm
		, (SELECT USER_NM FROM SY_USER WHERE USER_ID = A.TESTER_ID) testerNm
		, TO_CHAR(A.TEST_DT, 'YYYY-MM-DD') testDt
		, (SELECT USER_NM FROM SY_USER WHERE USER_ID = A.OPETR_ID) opetrNm
		, TO_CHAR(A.PROCESS_DT, 'YYYY-MM-DD') processDt
		, A.PROCESS_TIME
		, A.PROGRS_SITTN_CODE
		, A.TEST_CN
		, A.PROCESS_CN
		, A.TEST_SE_CODE
		, (SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE CMMN_CODE = A.PROGRS_SITTN_CODE) progrsSittnCodeNm
		, A.ATCHMNFL_SEQNO

		FROM PM_UNIT_TEST A
		INNER JOIN PM_PRJCT_MENU B ON A.PRJCT_MENU_SEQNO = B.PRJCT_MENU_SEQNO
		INNER JOIN PM_PRJCT C ON B.PRJCT_SEQNO = C.PRJCT_SEQNO
		LEFT JOIN SY_USER D ON A.OPETR_ID = D.USER_ID
		LEFT JOIN SY_USER E ON B.CHARGER_ID = E.USER_ID

		WHERE A.DELETE_AT = 'N'
    	AND A.UNIT_TEST_SEQNO = 1;


SELECT * FROM PM_PRJCT_MENU
WHERE PRJCT_MENU_SEQNO = 21;


SELECT * FROM SY_INSPCT_INSTT;

