
SELECT * FROM PM_PRJCT;

SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM PM_PRJCT_MENU;

UPDATE PM_PRJCT_MENU SET
DELETE_AT = 'N';

SELECT SQ_PM_PRJCT_MENU.NEXTVAL FROM DUAL;

SELECT B.PRJCT_SEQNO VALUE, B.PRJCT_NM KEY FROM PM_PRJCT_CHARGER A
INNER JOIN PM_PRJCT B ON A.PRJCT_SEQNO = B.PRJCT_SEQNO
WHERE A.DELETE_AT = 'N'
AND A.USE_AT = 'Y'
AND B.DELETE_AT = 'N'
AND B.USE_AT = 'Y'
AND A.CHARGER_ID = 1;

SELECT * FROM PM_PRJCT_MENU
WHERE DELETE_AT = 'N'
AND USE_AT = 'Y';


SELECT
			A.CHARGER_ID VALUE
			, B.USER_NM KEY

		FROM PM_PRJCT_MENU A
		INNER JOIN SY_USER B ON A.CHARGER_ID = B.USER_ID

		WHERE PRJCT_MENU_SEQNO = 1
			AND A.DELETE_AT = 'N'
			AND A.USE_AT = 'Y';



SELECT
	B.USER_ID VALUE
  ,B.USER_NM KEY
FROM PM_PRJCT_CHARGER A
INNER JOIN SY_USER B ON A.CHARGER_ID = B.USER_ID

WHERE A.PRJCT_SEQNO = 1
	AND A.DELETE_AT = 'N'
  AND A.USE_AT = 'Y'
  AND B.DELETE_AT = 'N'
  AND B.USE_AT = 'Y';


SELECT * FROM PM_UNIT_TEST;

SELECT * FROM PM_PRJCT_CHARGER WHERE CHARGER_ID = 1;

SELECT * FROM PM_PRJCT_CHARGER
WHERE PRJCT_SEQNO IN (SELECT PRJCT_SEQNO FROM PM_PRJCT_CHARGER WHERE CHARGER_ID = 1);


SELECT * FROM PM_UNIT_TEST A
INNER JOIN SY_USER B ON A.OPETR_ID = B.USER_ID
WHERE A.DELETE_AT = 'Y'
AND A.USE

OPETR_ID;


SELECT B.USER_ID, B.USER_NM FROM PM_UNIT_TEST A
INNER JOIN SY_USER B ON A.OPETR_ID = B.USER_ID
WHERE UNIT_TEST_SEQNO = 26;



SELECT * FROM SY_ATCHMNFL;
SELECT * FROM SY_ATCHMNFL_DETAIL;

SELECT * FROM PM_UNIT_TEST;

SELECT * FROM SY_BBS_SNTNC;
SELECT * FROM SY_BBS_ANSWER;