SELECT * FROM SY_MENU
ORDER BY MENU_SEQNO;

SELECT * FROM SY_MENU
WHERE MENU_SEQNO = 10600;

SELECT * FROM SY_MENU
WHERE MENU_NM IN ('傍烹内靛包府', '鼻茄包府','皋春包府');

SELECT * FROM SY_MENU
WHERE MENU_SEQNO = 9;

SELECT * FROM SY_MENU
WHERE MENU_NM IN ('炼流 包府', '荤侩磊 包府');

SELECT * FROM SY_MENU
WHERE MENU_URL IS NULL;

SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_MENU;
SELECT * FROM SY_AUTHOR_USER;


SELECT * FROM SY_AUTHOR_MENU A
LEFT JOIN SY_AUTHOR_USER B ON A.AUTHOR_CODE = B.AUTHOR_CODE;

SELECT * FROM SY_LANG_MASTR
WHERE LANG_CODE = 'C000000232';

SELECT * FROM SY_USER;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'SY09';



