SELECT * FROM SY_MENU
ORDER BY MENU_SEQNO DESC;
SELECT * FROM SY_LANG_MENU;

SELECT * FROM SY_USER;
SELECT * FROM SY_AUTHOR_USER;
SELECT * FROM SY_AUTHOR_MENU
ORDER BY MENU_SEQNO DESC;

SELECT * FROM AT_EXPR_HIST;
SELECT * FROM AT_EXPR_HIST
ORDER BY HIST_SEQNO DESC;




