/* */
SELECT * FROM RS_PCN;
SELECT * FROM RS_PCN_CHANGEPOINT;


SELECT * FROM SY_MENU;

SELECT A.MENU_SEQNO, A.MENU_NM, B.CHARGER_NM FROM SY_MENU A
LEFT JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY MENU_SEQNO;

SELECT * FROM SY_UNIT;

SELECT * FROM SY_UNIT_TEST;
SELECT * FROM SY_MENU_ACCTO_CHARGER;

MERGE
INTO SY_MENU A
USING (SELECT * FROM SY_MENU_ACCTO_CHARGER
				WHERE MENU_SEQNO = 19
) B
ON A.MENU_SEQNO = B.MENU_SEQNO AND B.CHARGER_NM IN NULL
WHEN MATCHED THEN
	INSERT INTO SY_MENU_ACCTO_CHARGER (B.MENU_SEQNO, B.CHARGER_NM)
  VALUES (19,'관리자')
WHEN NOT MATCHED THEN
	UPDATE SET
  B.CHARGER_NM = '관리자';

SELECT * FROM SY_MENU_ACCTO_CHARGER
WHERE MENU_SEQNO = 19;


MERGE INTO (SELECT * FROM SY_MENU_ACCTO_CHARGER
  			WHERE CHARGER_NM IS NOT NULL
        AND MENU_SEQNO = 20
				) A
USING SY_MENU B
ON (A.MENU_SEQNO = B.MENU_SEQNO)
WHEN MATCHED THEN
	UPDATE SET
  A.CHARGER_NM = '관리자'
  WHERE A.MENU_SEQNO = 20
WHEN NOT MATCHED THEN
	INSERT (A.MENU_SEQNO, A.CHARGER_NM)
  VALUES (20, '관리자');


SELECT * FROM SY_MENU_ACCTO_CHARGER
ORDER BY MENU_SEQNO;

SELECT * FROM SY_MENU;
SELECT * FROM SY_MENU_ACCTO_CHARGER
WHERE CHARGER_NM IS NOT NULL
AND MENU_SEQNO = 22;
INSERT INTO SY_MENU_ACCTO_CHARGER (MENU_SEQNO, CHARGER_NM)
VALUES (19, '관리자');


COMMIT;


INSERT INTO SY_MENU_ACCTO_CHARGER
VALUES (49, '없음');

SELECT * FROM SY_MENU_ACCTO_CHARGER;

DELETE FROM SY_MENU_ACCTO_CHARGER
WHERE CHARGER_NM = '없음';

SELECT A.MENU_SEQNO, A.MENU_NM, B.CHARGER_NM FROM SY_MENU A
LEFT JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY MENU_SEQNO ASC;


MERGE INTO (SELECT * FROM SY_MENU_ACCTO_CHARGER WHERE MENU_SEQNO = 22) A
USING SY_MENU B
ON (A.MENU_SEQNO = B.MENU_SEQNO)
WHEN MATCHED THEN
	UPDATE SET CHARGER_NM = '관리'
WHEN NOT MATCHED THEN
	INSERT (A.MENU_SEQNO, A.CHARGER_NM)
  VALUES (22, '관리');

SELECT * FROM SY_MENU_ACCTO_CHARGER;

MERGE INTO SY_MENU_ACCTO_CHARGER
USING DUAL
ON (MENU_SEQNO = 22)
WHEN MATCHED THEN
	UPDATE SET CHARGER_NM = '관리자'
WHEN NOT MATCHED THEN
	INSERT (MENU_SEQNO, CHARGER_NM)
  VALUES (22, '관리자');



SELECT * FROM SY_MENU;
SELECT * FROM SY_MENU_ACCTO_CHARGER;
SELECT * FROM SY_MENU_ACCTO_CHARGER WHERE MENU_SEQNO = 22;

SELECT A.MENU_SEQNO AS VALUE, A.MENU_NM AS KEY FROM SY_MENU A
LEFT JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY MENU_SEQNO;

SELECT A.MENU_SEQNO AS VALUE, A.MENU_NM AS KEY FROM SY_MENU A
JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY A.MENU_SEQNO;

SELECT * FROM SY_UNIT_TEST A
LEFT JOIN SY_MENU B ON A.MENU_SEQNO = B.MENU_SEQNO
LEFT JOIN SY_MENU_ACCTO_CHARGER C ON A.MENU_SEQNO = C.MENU_SEQNO
WHERE 1=1
ORDER BY A.MENU_SEQNO;



SELECT * FROM SY_CMMN_CODE
WHERE CMMN_CODE_NM LIKE '%완료%';

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'RS34';

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'RS30';


SELECT SQ_SY_UNIT_TEST.NEXTVAL FROM DUAL;

SELECT * FROM SY_UNIT_TEST;

SELECT * FROM RS_PCN;

INSERT INTO SY_UNIT_TEST
VALUES(
	SQ_SY_UNIT_TEST.NEXTVAL,
  19,
  '관리자',
  '테스트내용',
  '2022-05-04',
  'Y',
  '처리내용',
  '2022-05-06',
	'ip',
  'N',
  1,
  SYSDATE
);

UPDATE SY_UNIT_TEST SET
DELETE_AT = 'N',
LAST_CHANGER_ID = 1,
LAST_CHANGE_DT = SYSDATE,
RM = '비고'
WHERE UNIT_TEST_SEQNO = 31;

SELECT * FROM SY_UNIT_TEST;

COMMIT;

UPDATE SY_UNIT_TEST SET
TESTER_NM = 10,
TEST_CN = '테스트 내용',
TEST_DTE = '2022-05-05',
PROCESS_AT = 'Y',
PROCESS_CN = '처리 내용',
PROCESS_DTE = '2022-05-07',
LAST_CHANGER_ID = 1,
LAST_CHANGE_DT = SYSDATE,
RM = '비고비고';


SELECT * FROM SY_UNIT_TEST A
LEFT JOIN SY_MENU B ON A.MENU_SEQNO = B.MENU_SEQNO
LEFT JOIN SY_MENU_ACCTO_CHARGER C ON A.MENU_SEQNO = C.MENU_SEQNO
WHERE A.DELETE_AT = 'N'
AND A.MENU_SEQNO = 8;

UPDATE SY_UNIT_TEST SET
DELETE_AT = 'N';

COMMIT;


DELETE FROM SY_UNIT_TEST;
DELETE FROM SY_MENU_ACCTO_CHARGER
WHERE MENU_SEQNO = 19;

ROLLBACK;

SELECT CHARGER_NM FROM SY_MENU_ACCTO_CHARGER
WHERE MENU_SEQNO = 8;

SELECT * FROM SY_MENU;
SELECT * FROM SY_MENU_ACCTO_CHARGER;
SELECT * FROM SY_UNIT_TEST;

SELECT A.MENU_SEQNO, A.MENU_NM, B.CHARGER_NM, A.MENU_URL FROM SY_MENU A
LEFT JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
WHERE A.MENU_URL IS NOT NULL
ORDER BY A.MENU_SEQNO;


SELECT * FROM SY_UNIT_TEST;



SELECT
CASE
	WHEN PROCESS_AT = 'Y' THEN (SELECT '완료' AS processAtNm FROM DUAL)
  WHEN PROCESS_AT = 'W' THEN (SELECT '보류' AS processAtNm FROM DUAL)
  ELSE (SELECT '미완료' AS processAtNm FROM DUAL)
END AS processAtNm,
TESTER_NM
FROM SY_UNIT_TEST;

SELECT * FROM SY_UNIT_TEST;

SELECT * FROM SY_MENU_ACCTO_CHARGER
ORDER BY MENU_SEQNO;

DELETE FROM SY_MENU_ACCTO_CHARGER
WHERE MENU_SEQNO = 10;

COMMIT;

SELECT * FROM SY_UNIT_TEST;





