SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

UPDATE SY_USER SET
DELETE_AT = 'N'
WHERE USER_ID = 3316;

COMMIT;

SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_USER;


SELECT
	MAX(B.USER_ID) USER_ID
  , B.USER_NM
  , MAX(B.LOGIN_ID) LOGIN_DE
FROM SY_AUTHOR_USER A
LEFT JOIN SY_USER B ON A.USER_ID = B.USER_ID
WHERE B.USER_ID NOT IN (SELECT USER_ID FROM SY_AUTHOR_USER WHERE AUTHOR_CODE = 41)
GROUP BY B.USER_NM;

SELECT *
FROM SY_AUTHOR_USER A
LEFT JOIN SY_USER B ON A.USER_ID = B.USER_ID
WHERE B.USER_ID NOT IN (SELECT USER_ID FROM SY_AUTHOR_USER WHERE AUTHOR_CODE = 41);


SELECT * FROM SY_USER A
LEFT JOIN SY_AUTHOR_USER B ON A.USER_ID = B.USER_ID
WHERE A.USER_ID NOT IN (SELECT USER_ID FROM SY_AUTHOR_USER WHERE AUTHOR_CODE = 41);

SELECT COUNT(*) FROM SY_USER;

SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

DELETE FROM SY_USER
WHERE DELETE_AT = 'Y';

COMMIT;

SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_MENU;
SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM SY_MENU
ORDER BY MENU_SEQNO;

DELETE FROM SY_MENU
WHERE MENU_SEQNO IN (;

UPDATE SY_MENU SET
UPPER_MENU_SEQNO = 43
WHERE MENU_SEQNO = 44;

COMMIT;

SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM01';

SELECT * FROM SY_UNIT_TEST;


SELECT * FROM SY_MENU;

UPDATE SY_MENU SET
SORT_ORDR = 200000
WHERE MENU_SEQNO = 50;

COMMIT;

SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_CHARGER;
SELECT * FROM PM_PRJCT_MENU;

SELECT * FROM SY_USER;

SELECT * FROM SY_CMMN_CODE;

COMMIT;

ROLLBACK;

SELECT COUNT(*) FROM SY_CMMN_CODE;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM01';

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM02';

SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_CHARGER;
SELECT * FROM PM_PRJCT_MENU;


SELECT * FROM PM_UNIT_TEST;

SELECT * FROM SY_CMMN_CODE;




