
SELECT B.MENU_NM,A.*  FROM SY_UNIT_TEST A
LEFT JOIN SY_MENU B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY UNIT_TEST_SEQNO DESC;

SELECT * FROM SY_BBS;
SELECT * FROM SY_BBS_ANSWER;
SELECT * FROM SY_BBS_SNTNC;

SELECT * FROM SY_CMMN_CODE;