SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_MENU;
SELECT * FROM SY_AUTHOR_USER;


COMMENT ON COLUMN SY_AUTHOR.NEW_AUTHOR_APPLC_AT IS '신규 권한 적용 여부';

SELECT * FROM SY_USER A
LEFT JOIN SY_AUTHOR_USER B ON A.USER_ID = B.USER_ID
LEFT JOIN SY_AUTHOR C ON B.AUTHOR_CODE = C.AUTHOR_CODE;


SELECT COUNT(*) FROM SY_USER;

SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT;


SELECT * FROM SY_USER A
LEFT JOIN SY_INSPCT_INSTT_USER B ON A.USER_ID = B.USER_ID
LEFT JOIN SY_INSPCT_INSTT C ON B.INSPCT_INSTT_SEQNO = C.INSPCT_INSTT_SEQNO
WHERE 1=1
AND A.DELETE_AT = 'N'
AND C.INSPCT_INSTT_SEQNO = 52;

SELECT * FROM SY_AUTHOR_MENU;


-- 기본 권한 추가.
SELECT * FROM SY_AUTHOR_USER;
-- GW 추가
SELECT * FROM SY_INSPCT_INSTT_USER;

INSERT INTO SY_INSPCT_INSTT_USER
		VALUES (
			43
			,1
		  ,SYSDATE
		  ,1
		  , 43
		);

UPDATE SY_INSPCT_INSTT_USER SET
GW_ORGNZT_INTRFC_KEY = NULL
WHERE USER_ID = 1;

COMMIT;

COMMENT ON COLUMN SY_INSPCT_INSTT_USER.GW_ORGNZT_INTRFC_KEY IS 'GW 조직 인터페이스 키';


SELECT * FROM SY_AUTHOR_USER;


MERGE INTO SY_AUTHOR_USER
USING DUAL
ON (USER_ID = 121)
WHEN MATCHED THEN
	UPDATE SET
  	AUTHOR_CODE = 1
    ,INQIRE_AUTHOR_AT = 'Y'
    ,STRE_AUTHOR_AT = 'Y'
    ,DELETE_AUTHOR_AT = 'Y'
    ,OUTPT_AUTHOR_AT = 'Y'
    ,LAST_CHANGER_ID = 1
    ,LAST_CHANGE_DT = SYSDATE
WHEN NOT MATCHED THEN
	INSERT (
		AUTHOR_CODE
		,USER_ID
		,INQIRE_AUTHOR_AT
    ,STRE_AUTHOR_AT
    ,DELETE_AUTHOR_AT
    ,OUTPT_AUTHOR_AT
    ,LAST_CHANGER_ID
    ,LAST_CHANGE_DT
  )
  VALUES (
  	21
    ,104
    ,'Y'
    ,'Y'
    ,'Y'
    ,'Y'
    ,1
    ,SYSDATE
  );

SELECT * FROM SY_AUTHOR_USER;

SELECT AUTHOR_CODE FROM SY_AUTHOR
WHERE NEW_AUTHOR_APPLC_AT = 'Y';


ROLLBACK;

SELECT COUNT(*) FROM SY_AUTHOR_USER;
SELECT COUNT(*) FROM SY_USER;


SELECT * FROM SY_AUTHOR_MENU;

SELECT * FROM SY_AUTHOR_USER;

DELETE FROM SY_AUTHOR_USER
WHERE USER_ID != 1;

ROLLBACK;
COMMIT;

SELECT * FROM SY_AUTHOR_USER;

SELECT COUNT(*) FROM SY_AUTHOR_USER;

SELECT * FROM SY_AUTHOR;


SELECT
			A.USER_ID,
			A.USER_NM,
			A.LOGIN_ID

		FROM SY_USER A
		LEFT JOIN SY_AUTHOR_USER B ON A.USER_ID = B.USER_ID;
	--	LEFT JOIN SY_AUTHOR C ON B.AUTHOR_CODE = C.AUTHOR_CODE AND C.AUTHOR_CODE = 21;


SELECT
	C.USER_ID,
	C.USER_NM,
	C.LOGIN_ID
FROM (SELECT * FROM SY_AUTHOR WHERE AUTHOR_CODE != 21) A
	LEFT JOIN SY_AUTHOR_USER B ON A.AUTHOR_CODE = B.AUTHOR_CODE
	LEFT JOIN SY_USER C ON B.USER_ID = C.USER_ID
WHERE 1=1
	AND C.USE_AT = 'Y'
  AND C.DELETE_AT = 'N'
ORDER BY C.USER_NM;


SELECT * FROM SY_AUTHOR_USER
WHERE USER_ID = 1;


SELECT * FROM SY_INSPCT_INSTT_USER;

DELETE FROM SY_INSPCT_INSTT_USER
WHERE USER_ID = 1;

SELECT COUNT(*) FROM SY_INSPCT_INSTT_USER;

COMMIT;

SELECT COUNT(*) FROM SY_USER;


SELECT * FROM SY_AUTHOR_USER
WHERE USER_ID = 1;


SELECT * FROM SY_AUTHOR;


SELECT * FROM AT_MENU_USE_HIST;


SELECT SQ_SY_AUTHOR.NEXTVAL FROM DUAL;

SELECT SQ_SY_USER.NEXTVAL FROM DUAL;
SELECT SQ_SY_INSPCT_INSTT.NEXTVAL FROM DUAL;


