SELECT * FROM SY_MENU;



		SELECT
						MAX(DECODE(LEVEL,1,SM.MENU_NM))MENU_NM4,
            MAX(DECODE(LEVEL,1,SM.MENU_SEQNO))MENU_CD4,
            MAX(DECODE(LEVEL,2,SM.MENU_NM))MENU_NM3,
            MAX(DECODE(LEVEL,2,SM.MENU_SEQNO))MENU_CD3,
            MAX(DECODE(LEVEL,3,SM.MENU_NM))MENU_NM2,
            MAX(DECODE(LEVEL,3,SM.MENU_SEQNO))MENU_CD2,
            MAX(DECODE(LEVEL,4,SM.MENU_NM))MENU_NM1,
            MAX(DECODE(LEVEL,4,SM.MENU_SEQNO))MENU_CD1
        FROM SY_MENU SM
        WHERE SM.USE_AT = 'Y'
        START WITH SM.MENU_URL = #{menuUrl}
        CONNECT BY PRIOR SM.UPPER_MENU_SEQNO = SM.MENU_SEQNO;


SELECT * FROM SY_MENU
ORDER BY MENU_SEQNO;


SELECT * FROM SY_USER;

SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_MENU;
SELECT * FROM SY_AUTHOR_USER;

UPDATE SY_USER SET
USE_AT = 'Y';


SELECT * FROM SY_USER;


SELECT * FROM SY_AUTHOR;

DELETE FROM SY_AUTHOR
WHERE AUTHOR_CODE = 3;


UPDATE SY_AUTHOR SET
LAST_CHANGER_ID = 3
WHERE AUTHOR_CODE = 3;

COMMIT;

SELECT * FROM SY_MENU;

DELETE FROM SY_MENU
WHERE MENU_SEQNO = 21;


SELECT * FROM SY_EXCP_LOG;


SELECT * FROM SY_INSPCT_INSTT;



