SELECT * FROM PM_PRJCT_MENU
ORDER BY PRJCT_MENU_SEQNO;




INSERT INTO PM_PRJCT_MENU VALUES(
	SQ_PM_PRJCT_MENU.NEXTVAL
  , 1
	, 1
	, (SELECT USER_ID FROM SY_USER WHERE USER_NM = '관리자1' AND
  ,	'PM02000001'
  , '메뉴이름'
  , 'menuId'
  , 'fileName'
  , NULL
  , NULL
  , 'N'
  , 'N'
  , '비고'
  , 'Y'
  , 'N'
  , 1
  , SYSDATE
);

ROLLBACK;
COMMIT;

SELECT CHARGER_ID FROM PM_PRJCT_CHARGER
WHERE CHARGER_ID IN (SELECT USER_ID FROM SY_USER WHERE USER_NM = '관리자1')
AND PRJCT_SEQNO = 1;


SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_MENU;


UPDATE PM_PRJCT_MENU SET
	UPPER_PRJCT_MENU_SEQNO = 1
  , PRJCT_SEQNO = 1
  , CHARGER_ID =	(
  								SELECT CHARGER_ID
									FROM PM_PRJCT_CHARGER
			 						WHERE CHARGER_ID IN (SELECT USER_ID FROM SY_USER WHERE USER_NM = 'test1')
			 						AND PRJCT_SEQNO = 1
  							)
  , MENU_SE_CODE = 'PM02000003'
  , MENU_NM = '메뉴 수정 테스트'
  , MENU_ID = 'sys'
  , FILE_NM = 'updateTest'
  , RM = '비고 수정 테스트'
  , USE_AT = 'Y'
  , LAST_CHANGER_ID = 1
  , LAST_CHANGE_DT = SYSDATE
WHERE PRJCT_MENU_SEQNO = 43;

COMMIT;


SELECT * FROM PM_PRJCT_MENU;

UPDATE PM_PRJCT_MENU SET
	DELETE_AT = 'N';


SELECT * FROM PM_UNIT_TEST;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM04';

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM03';


SELECT * FROM PM_UNIT_TEST;
SELECT * FROM PM_PRJCT_MENU;


SELECT
	PRJCT_MENU_SEQNO VALUE
	, MENU_NM KEY
FROM PM_PRJCT_MENU
WHERE PRJCT_SEQNO = 1;


SELECT
	A.CHARGER_ID VALUE
	, B.USER_NM KEY
FROM PM_PRJCT_MENU A
INNER JOIN SY_USER B ON A.CHARGER_ID = B.USER_ID
WHERE PRJCT_MENU_SEQNO = 1;



SELECT * FROM PM_UNIT_TEST;

SELECT * FROM PM_PRJCT_MENU;

SELECT * FROM PM_PRJCT;


SELECT
	C.PRJCT_SEQNO
  , A.UNIT_TEST_SEQNO
  , A.PRJCT_MENU_SEQNO
  , A.TESTER_ID
  , A.OPETR_ID
  , A.RERGIST_NUMOT
	, C.PRJCT_NM
  , B.MENU_NM
  , (SELECT USER_NM FROM SY_USER WHERE USER_ID = B.CHARGER_ID) chargerNm
  , (SELECT USER_NM FROM SY_USER WHERE USER_ID = A.TESTER_ID) testerNm
  , TO_CHAR(A.TEST_DT, 'YYYY-MM-DD')
  , (SELECT USER_NM FROM SY_USER WHERE USER_ID = A.OPETR_ID) opetrNm
  , A.PROCESS_DT
  , A.PROCESS_TIME
  , A.PROGRS_SITTN_CODE
  , A.TEST_CN
  , A.PROCESS_CN
  ,(SELECT
FROM PM_UNIT_TEST A
INNER JOIN PM_PRJCT_MENU B ON A.PRJCT_MENU_SEQNO = B.PRJCT_MENU_SEQNO
INNER JOIN PM_PRJCT C ON B.PRJCT_SEQNO = C.PRJCT_SEQNO

WHERE A.DELETE_AT = 'N'
;

SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM PM_PRJCT_MENU;


CREATE SEQUENCE SQ_PM_UNIT_TEST;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM03';

SELECT * FROM PM_UNIT_TEST;


INSERT INTO PM_UNIT_TEST VALUES(
	SQ_PM_UNIT_TEST.NEXTVAL
  , 21
  , 1
  , SYSDATE
  , '테스트 내용'
  , 1
  , NULL
  , NULL
  , NULL
  , 'PM04000003'
	, 'PM03000002'
  , 0
  , 'N'
  , 1
  ,SYSDATE
);

COMMIT;


