SELECT * FROM RS_PCN;

SELECT * FROM SY_ENTRPS;

SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS A
INNER JOIN SY_ENTRPS_SE B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO
ORDER BY A.ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS A
ORDER BY A.ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC;




SELECT ENTRPS_SEQNO, COUNT(ENTRPS_SE_CODE) FROM SY_ENTRPS_SE
GROUP BY ENTRPS_SEQNO
ORDER BY ENTRPS_SEQNO DESC;

SELECT
	A.ENTRPS_SEQNO,
	MAX(A.ENTRPS_NM) entrpsNm,
  LISTAGG(B.ENTRPS_SE_CODE, ',') WITHIN GROUP(ORDER BY B.ENTRPS_SE_CODE) entrpsSeCode,
  MAX(B.USE_AT) useAt,
  CASE
  	WHEN LISTAGG(B.ENTRPS_SE_CODE, ',') WITHIN GROUP(ORDER BY B.ENTRPS_SE_CODE) LIKE '%SY08000001%' THEN 'Y'
    ELSE 'N'
  END entrpsSeCodeCus,
  CASE
  	WHEN LISTAGG(B.ENTRPS_SE_CODE, ',') WITHIN GROUP(ORDER BY B.ENTRPS_SE_CODE) LIKE '%SY08000002%' THEN 'Y'
    ELSE 'N'
  END entrpsSeCodeCoop
FROM SY_ENTRPS A
INNER JOIN SY_ENTRPS_SE B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO
GROUP BY A.ENTRPS_SEQNO
ORDER BY A.ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS_SE
WHERE ENTRPS_SEQNO = 128;


SELECT COUNT(*) FROM SY_ENTRPS_SE
WHERE ENTRPS_SEQNO = 1
AND ENTRPS_SE_CODE = '-';

DELETE SY_ENTRPS_SE
WHERE ENTRPS_SEQNO = 120
AND ENTRPS_SE_CODE = '-';

SELECT * FROM SY_ENTRPS_SE;

ROLLBACK;

SELECT * FROM SY_ENTRPS A
INNER JOIN SY_ENTRPS_SE B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO
WHERE A.ENTRPS_NM = 'ªË¡¶'
AND B.USE_AT = 'Y';

SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC;



MERGE INTO SY_ENTRPS_SE
USING DUAL
ON (ENTRPS_SEQNO = 123 AND ENTRPS_SE_CODE = '-')
WHEN MATCHED THEN
  UPDATE SET
    LAST_CHANGER_ID = 1,
    LAST_CHANGE_DT = SYSDATE
WHEN NOT MATCHED THEN
  INSERT
  VALUES(
    123,
    '-',
    1000,
    'Y',
    1,
    SYSDATE
  );

SELECT * FROM SY_ENTRPS
ORDER BY ENTRPS_SEQNO DESC;

SELECT
A.ENTRPS_SEQNO,
LISTAGG(B.ENTRPS_SE_CODE,',') WITHIN GROUP(ORDER BY B.ENTRPS_SE_CODE) FROM SY_ENTRPS A
INNER JOIN SY_ENTRPS_SE B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO
WHERE B.USE_AT = 'Y'
GROUP BY(A.ENTRPS_SEQNO)
ORDER BY A.ENTRPS_SEQNO DESC;


SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC, ENTRPS_SE_CODE;


DELETE FROM SY_ENTRPS_SE
WHERE ENTRPS_SEQNO = 132;

DELETE FROM SY_ENTRPS
WHERE ENTRPS_SEQNO = 132;

SELECT
	A.ENTRPS_SEQNO,
	CASE
  	WHEN B.ENTRPS_SE_CODE = 'SY08000001' THEN 'Y'
    ELSE 'N'
  END entrpsSeCodeCus,
  CASE
  	WHEN B.ENTRPS_SE_CODE = 'SY08000002' THEN 'Y'
    ELSE 'N'
  END entrpsSeCodeCoop
FROM SY_ENTRPS A
LEFT JOIN SY_ENTRPS_SE B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO
WHERE B.USE_AT = 'Y'
ORDER BY A.ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS
ORDER BY ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC;



