
SELECT * FROM SY_USER
WHERE LOGIN_ID = 'admin';


SELECT PKG_CRYPTO.DECRYPT('95588A192B33906557384AAA6395A923') FROM DUAL;



SELECT * FROM KL_WRHSDLVR;


SELECT
			RW.WRHSDLVR_SEQNO
			,RW.WRHSDLVR_SE_CODE
			,RW.WRHSDLVR_DEPT_CODE
			,RW.WRHSDLVRMAN_ID
			,(SELECT USER_NM FROM SY_USER WHERE RW.WRHSDLVRMAN_ID = USER_ID) AS WRHSDLVRMAN_NM
			,NVL(RW.DSUSE_DTE,RW.WRHSDLVR_DTE) AS WRHSDLVR_DTE
			,RW.WRHSDLVR_QY
			,RW.BRCD_CREAT_AT
			,RW.RM
			,RW.PRDUCT_SEQNO
			,KP.PRDUCT_NM
			,(SELECT CMMN_CODE_NM FROM SY_CMMN_CODE  WHERE CMMN_CODE = KP.RGNT_STTUS_CODE) AS RGNT_STTUS_CODE_NM
            ,KP.RGNT_STTUS_CODE
			,T.ENTRPS_NM
			,T.VALID_DTE
			,T.CNTNR_QY
			,T.CSTDY_PLACE_CODE
			,T.CSTDY_PLACE_CODE_NM
			,T.UNSEAL_DTE
			,T.USE_REALM
			,T.PRPOS_CODE_NM
			,T.CSTDY_STTUS_CODE_NM
			,T.PC
			,T.CTLG_NO
			,T.CAS_NO
			,T.STNDRD_DC
			,T.REGIST_NO
			,T.CONT
			,T.PRTDG_DC
			,T.MNFCTUR_INSTT_NM
			,T.MNFCTUR_NATION_NM
			,T.LOT_NO
			,T.CPCTY
			,T.DNSTY
			,T.PURCHSQY
			,T.PURCHS_DTE
			,T.PRDUCT_NO
			,SII.INSPCT_INSTT_NM AS DEPTNM
            ,(SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE CMMN_CODE = RW.WRHSDLVR_SE_CODE) AS WRHSDLVRSENM
         		    FROM KL_WRHSDLVR RW
              LEFT OUTER JOIN SY_INSPCT_INSTT SII ON SII.INSPCT_INSTT_CODE = RW.WRHSDLVR_DEPT_CODE
              LEFT OUTER JOIN KL_PRDUCT KP ON KP.PRDUCT_SEQNO = RW.PRDUCT_SEQNO
              LEFT OUTER JOIN
            	 (SELECT
						BB.ENTRPS_NM
						,RWX.WRHSDLVR_SEQNO
						,NVL(RWX.ETC_VALID_DTE,RWX.VALID_DTE) AS VALID_DTE
						,RWX.CNTNR_QY
						,RWX.CSTDY_PLACE_CODE
						,(SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE RWX.CSTDY_PLACE_CODE = CMMN_CODE) AS CSTDY_PLACE_CODE_NM
						,RWX.UNSEAL_DTE
						,RWX.USE_REALM
						,AA.CMMN_CODE_NM AS PRPOS_CODE_NM
						,AC.CMMN_CODE_NM AS CSTDY_STTUS_CODE_NM
						,RWX.PC
						,RWX.CTLG_NO
						,RWX.CAS_NO
						,RWX.STNDRD_DC
						,RWX.REGIST_NO
						,RWX.CONT
						,RWX.PRTDG_DC
						,RWX.MNFCTUR_INSTT_NM
						,RWX.MNFCTUR_NATION_NM
						,RWX.LOT_NO
						,RWX.CPCTY
						,RWX.DNSTY
						,RWX.PURCHSQY
						,RWX.PURCHS_DTE
						,RWX.PRDUCT_NO
                      FROM  KL_WRHSDLVR RWX
                  LEFT OUTER JOIN SY_ENTRPS BB ON RWX.ENTRPS_SEQNO = BB.ENTRPS_SEQNO
                  LEFT OUTER JOIN SY_CMMN_CODE AA ON RWX.PRPOS_CODE =AA.CMMN_CODE
                  LEFT OUTER JOIN SY_CMMN_CODE AC ON RWX.CSTDY_STTUS_CODE =AC.CMMN_CODE
                  WHERE 1=1
                  AND RWX.PRDUCT_SEQNO =  '2050' /**P*/
                  AND RWX.WRHSDLVR_SE_CODE = 'KL08A00001'


                  ) T
                  ON (RW.UPPER_WRHSDLVR_SEQNO= T.WRHSDLVR_SEQNO OR RW.WRHSDLVR_SEQNO = T.WRHSDLVR_SEQNO)

                  WHERE 1=1

        	AND RW.PRDUCT_SEQNO =  '2050' /**P*/



        ORDER BY RW.WRHSDLVR_DTE,RW.WRHSDLVR_SEQNO DESC;


SELECT * FROM KL_WRHSDLVR;


SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'KL08';

SELECT * FROM KL_EQPMN;

-- 점검기준
SELECT * FROM KL_EQPMN_CHCK_STDR;

-- 수리 이력
SELECT * FROM KL_EQPMN_REPAIR_HIST
ORDER BY EQPMN_REPAIR_HIST_SEQNO DESC;

-- 교정 이력
SELECT * FROM KL_EQPMN_CRRCT_HIST;

-- 전자 매체
SELECT * FROM KL_ELCTRN_MEDIA
ORDER BY ELCTRN_MEDIA_SEQNO DESC;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'KL10';

-- 접수
SELECT * FROM IM_RCEPT;

-- 접수 항목
SELECT EXPRIEM_EXPSS_FEE, EXPRIEM_FEE FROM IM_RCEPT_EXPR_IEM;


-- 접수 시료
SELECT * FROM IM_RCEPT_SPLORE
ORDER BY RCEPT_SPLORE_SEQNO DESC;

SELECT * FROM IM_RCEPT_ENG_INFO;
SELECT * FROM IM_RCEPT_EXPR_IEM;
SELECT * FROM IM_RCEPT_HELP_DEPT;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'IM04';

SELECT * FROM SY_CMMN_CODE
WHERE CMMN_CODE_NM = '수거검사';

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'IM02';

SELECT * FROM IM_EXPRDIARY
ORDER BY EXPRDIARY_SEQNO DESC;

-- 업체
SELECT * FROM SY_ENTRPS;

-- 문자 발송 이력
SELECT * FROM CF_MSG_SEND;

-- 급행 수수료 여부
SELECT
  A.RCEPT_SEQNO
  ,A.RCEPT_DTE
  ,A.RCEPT_NO
  ,B.RCEPT_SPLORE_SEQNO
  ,B.SPLORE_RCEPT_NO
  ,B.SPLORE_NM
  ,DECODE(B.EXPSS_FEE_AT,'Y','급행','일반') AS EXPSS_FEE_AT
  ,DECODE(B.EXPSS_FEE_AT,'Y',C.EXPRIEM_EXPSS_FEE,C.EXPRIEM_FEE) AS FEE
  ,C.RCEPT_EXPR_IEM_SEQNO
  ,C.EXPRIEM_NM

FROM IM_RCEPT A
JOIN IM_RCEPT_SPLORE B ON A.RCEPT_SEQNO = B.RCEPT_SEQNO
JOIN IM_RCEPT_EXPR_IEM C ON B.RCEPT_SPLORE_SEQNO = C.RCEPT_SPLORE_SEQNO
JOIN IM_RCEPT_ENTRPS D ON A.RCEPT_SEQNO = D.RCEPT_SEQNO

WHERE 1=1
  AND A.DELETE_AT = 'N'
  AND A.INSPCT_INSTT_CODE = 'I000001'
  AND B.DELETE_AT = 'N'
  AND C.DELETE_AT = 'N'
  AND A.RCEPT_DTE   >=    '2019-06-01' /**P*/
  AND A.RCEPT_DTE   <=    '2022-07-18' /**P*/
  AND D.ENTRPS_SE_CODE =  'IM23000001' /**P*/

ORDER BY A.RCEPT_SEQNO;








