SELECT * FROM IM_RCEPT_ENTRPS A
INNER JOIN IM_RCEPT_ENG_INFO B ON A.RCEPT_SEQNO = B.RCEPT_SEQNO;


SELECT * FROM IM_RCEPT_ENG_INFO;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'IM42';


SELECT * FROM IM_ISSU;

SELECT * FROM IM_RCEPT_ENTRPS;

SELECT * FROM CN_PRDLST;


SELECT * FROM SY_USER;

SELECT B.ENG_ADRES FROM IM_RCEPT_SPLORE A
LEFT JOIN IM_RCEPT_ENTRPS B ON A.RCEPT_SEQNO = B.RCEPT_SEQNO
WHERE SPLORE_RCEPT_NO = 'AN2108A0002-004';


SELECT * FROM KL_WRHSDLVR;

SELECT * FROM IM_RCEPT_ENTRPS;


SELECT * FROM IM_RCEPT_ENG_INFO;


SELECT * FROM SY_ENTRPS;


SELECT * FROM IM_RCEPT_SPLORE;


SELECT * FROM IM_RCEPT_SPLORE;


SELECT A.TELNO_ENG_NM, A.FXNUM_ENG_NM FROM IM_RCEPT_ENTRPS A;

SELECT A.ORGPLCE_NM FROM IM_RCEPT_SPLORE A;


SELECT A.INSPCT_PURPS_CODE FROM IM_RCEPT A;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'IM02';



SELECT A.ENTRPS_ENG_NM FROM SY_ENTRPS A
WHERE A.ENTRPS_ENG_NM = 'shs';


SELECT * FROM IM_RCEPT_ENTRPS A;


SELECT * FROM IM_RCEPT_ENTRPS A
LEFT JOIN SY_ENTRPS_CHARGER B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO AND A.CHARGER_MOBLPHON = B.CHARGER_MOBLPHON AND A.CHARGER;

SELECT * FROM SY_ENTRPS_CHARGER A
WHERE A.CHARGER_NM = '褕⑷撥';






SELECT * FROM SY_INSPCT_INSTT;


SELECT * FROM SY_ENTRPS A
FULL JOIN SY_ENTRPS_CHARGER B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO
WHERE ENTRPS_NM = '六六六六';


SELECT A.CHARGER FROM IM_RCEPT_ENTRPS A;
SELECT * FROM SY_ENTRPS_CHARGER;


SELECT * FROM IM_RCEPT_ENTRPS;

SELECT * FROM IM_RCEPT_ENG_INFO;


