SELECT * FROM RS_PCN;

SELECT * FROM SY_ENTRPS;
SELECT * FROM SY_ENTRPS_SE;

DELETE FROM SY_ENTRPS
WHERE ENTRPS_SEQNO >= 30;

DELETE FROM SY_ENTRPS_SE
WHERE ENTRPS_SEQNO >= 30;

COMMIT;

SELECT * FROM SY_ENTRPS;
SELECT * FROM SY_ENTRPS_SE;
SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'SY08';



