
SELECT * FROM RS_PCN;
SELECT CHRG_DEPT_CODE FROM RS_PCN;
SELECT * FROM RS_PCN_CHANGEPOINT;

/* 담당부서 */
SELECT * FROM SY_INSPCT_INSTT;

/* 고객사 */
SELECT * FROM SY_ENTRPS;

SELECT * FROM CM_SANCTN_INFO
WHERE SANCTN_PROGRS_SITTN_CODE = 'CM01000003';

SELECT * FROM CM_SANCTN;
SELECT * FROM CM_SANCTN_INFO;
SELECT * FROM RS_PCN;
SELECT * FROM CM_CN;
SELECT * FROM RS_PCN;
SELECT * FROM RS_AUDIT;

SELECT * FROM RS_AUDIT_CAR
WHERE CAR_NO = 'FCC-CAR-22-04-003';
SELECT * FROM CM_SANCTN
WHERE SANCTN_SEQNO = 36;

SELECT * FROM CM_CN
WHERE CN_SEQNO = 35;


/* 공통 코드 */
SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'CM01';


/* 첨부 파일 */
SELECT * FROM SY_ATCHMNFL
WHERE ATCHMNFL_SEQNO = 62;
SELECT * FROM SY_ATCHMNFL_DETAIL
WHERE ATCHMNFL_SEQNO = 62
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM RS_PCN
ORDER BY PCN_SEQNO DESC;

SELECT * FROM RS_PCN
WHERE ATCHMNFL_SEQNO != 0;

/* 담당자 */
SELECT * FROM RS_PCN;
SELECT * FROM SY_USER;

SELECT * FROM SY_INSPCT_INSTT;

/* 결재선 */
SELECT * FROM RS_PCN;
SELECT * FROM SY_CMMN_CODE
WHERE CMMN_CODE = 'CM05000002';


/* 결재 */
SELECT * FROM RS_PCN;
SELECT * FROM RS_AUDIT;
SELECT * FROM CM_SANCTN;
SELECT * FROM CM_SANCTN_INFO;
SELECT * FROM SY_SANCTN_LINE;
SELECT * FROM SY_SANCTN_LINE_SANCTNER;
SELECT * FROM SY_CMMN_CODE
WHERE CMMN_CODE = 'CM02000003';


/* 검토 */
SELECT * FROM CM_EXMNT
ORDER BY EXMNT_SEQNO;
SELECT * FROM CM_EXMNT_HIST
ORDER BY EXMNT_SEQNO;
SELECT * FROM RS_AUDIT;

SELECT * FROM CM_EXMNT;
SELECT * FROM RS_PCN;

