SELECT * FROM PM_PRJCT_MENU;


SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM02';



SELECT B.USER_ID, B.USER_NM, A.PRJCT_SEQNO FROM PM_PRJCT_CHARGER A
INNER JOIN SY_USER B ON A.CHARGER_ID = B.USER_ID
ORDER BY B.USER_NM;

SELECT COUNT(*) FROM PM_PRJCT_CHARGER A
WHERE A.PRJCT_SEQNO = 22;


SELECT * FROM SY_USER;

SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM PM_PRJCT_MENU;

SELECT
			B.USER_ID changerId
			, B.USER_NM changerNm
			, A.PRJCT_SEQNO
		FROM PM_PRJCT_CHARGER A
		INNER JOIN SY_USER B ON A.CHARGER_ID = B.USER_ID

		ORDER BY B.USER_NM;


SELECT * FROM SY_USER
ORDER BY USER_ID;

SELECT * FROM PM_PRJCT_MENU;

INSERT INTO PM_PRJCT_MENU VALUES
(


);
