SELECT * FROM AT_LOGIN_HIST
ORDER BY HIST_SEQNO DESC;

SELECT * FROM AT_MENU_USE_HIST
ORDER BY HIST_SEQNO DESC;

SELECT * FROM SY_AUTHOR;

SELECT * FROM SY_AUTHOR_MENU
ORDER BY AUTHOR_CODE DESC;

SELECT * FROM SY_MENU
ORDER BY MENU_SEQNO DESC;

SELECT * FROM SY_ATCHMNFL_DETAIL
ORDER BY ATCHMNFL_SEQNO DESC;

SELECT * FROM CM_CN
ORDER BY CN_SEQNO DESC;

SELECT * FROM CM_WDTB
ORDER BY WDTB_SEQNO DESC;

SELECT * FROM CM_WDTB_TRGTER
ORDER BY WDTB_SEQNO DESC;

SELECT * FROM SY_INSPCT_INSTT
START WITH UPPER_INSPCT_INSTT_CODE IS NULL
CONNECT BY PRIOR INSPCT_INSTT_CODE = UPPER_INSPCT_INSTT_CODE
ORDER SIBLINGS BY INSPCT_INSTT_CODE DESC;

SELECT * FROM SY_EXCEL;
SELECT * FROM SY_EXCEL_HIST;
SELECT * FROM SY_EXCEL_CEL_MANAGE;


SELECT * FROM SY_EXCP_LOG
ORDER BY EXCP_LOG_SEQNO DESC;

SELECT * FROM SY_PRDUCT_CTMMNY
ORDER BY PRDUCT_CTMMNY_SEQNO DESC;

SELECT * FROM SY_MTRIL_SDSPC
ORDER BY MTRIL_SDSPC_SEQNO DESC;

SELECT B.* FROM SY_MTRIL A
LEFT JOIN SY_MTRIL_SDSPC B ON A.MTRIL_SEQNO = B.MTRIL_SEQNO
ORDER BY B.MTRIL_SEQNO DESC;





