SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_USER;

SELECT * FROM SY_INSPCT_INSTT;

DELETE FROM SY_INSPCT_INSTT
WHERE INSPCT_INSTT_SEQNO = 470;

SELECT COUNT(*) FROM SY_USER;

SELECT * FROM SY_AUTHOR
ORDER BY AUTHOR_CODE DESC;

SELECT * FROM SY_ENTRPS;
SELECT * FROM SY_EXCP_LOG
ORDER BY EXCP_LOG_SEQNO DESC;

SELECT * FROM SY_AUTHOR_USER
WHERE USER_ID = 159;

UPDATE SY_AUTHOR_USER SET
AUTHOR_CODE = 41
WHERE USER_ID = 159;

SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT SQ_SY_USER.NEXTVAL FROM DUAL;

SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_AUTHOR;

UPDATE SY_AUTHOR SET
NEW_AUTHOR_APPLC_AT = 'N';

SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT_USER
ORDER BY INSPCT_INSTT_SEQNO DESC;

SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

SELECT * FROM SY_INSPCT_INSTT
ORDER BY INSPCT_INSTT_SEQNO DESC;

SELECT * FROM SY_INSPCT_INSTT_USER;

INSERT INTO SY_INSPCT_INSTT_USER(
	INSPCT_INSTT_SEQNO
  , USER_ID
  , LAST_CHANGE_DT
  , LAST_CHANGER_ID
	, GW_ORGNZT_INTRFC_KEY
) VALUES (
 	43
 	,1
  ,SYSDATE
  ,1
  ,NULL
);

ROLLBACK;


SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

SELECT * FROM SY_INSPCT_INSTT_USER
ORDER BY USER_ID DESC;


SELECT * FROM SY_INSPCT_INSTT
WHERE INSPCT_INSTT_SEQNO = 761;

SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_USER;

UPDATE SY_USER SET
	LOGIN_ID = 'test101'
  , USER_NM = 'test101'
  , PASSWORD = (SELECT PKG_CRYPTO.ENCRYPT(1111) FROM DUAL)
  , MOBLPHON = '010-4444-4444'
  , EMAIL = 'abcd@abc.com'
  , LAST_CHANGER_ID = 1
  , USE_AT = 'Y'
  , LAST_CHANGE_DT = SYSDATE
WHERE USER_ID = 1;

ROLLBACK;

SELECT * FROM SY_INSPCT_INSTT_USER
ORDER BY INSPCT_INSTT_SEQNO DESC;

UPDATE SY_INSPCT_INSTT_USER SET
  LAST_CHANGE_DT = SYSDATE
  , LAST_CHANGER_ID = 1
WHERE INSPCT_INSTT_SEQNO = 761 AND USER_ID = 3321;

COMMIT;



UPDATE SY_USER SET
	DELETE_AT = 'Y'
WHERE USER_ID = 3321;


DELETE FROM SY_INSPCT_INSTT_USER
WHERE INSPCT_INSTT_SEQNO = 761 AND USER_ID = 3321;

ROLLBACK;


SELECT * FROM SY_INSPCT_INSTT_USER
ORDER BY USER_ID DESC;

SELECT * FROM SY_USER
WHERE USER_NM = 'test1123213';


SELECT COUNT(LOGIN_ID)
		FROM SY_USER
WHERE LOGIN_ID = 'admin';

SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

DELETE FROM SY_USER
WHERE USER_ID = 3363;

COMMIT;

SELECT * FROM SY_USER
ORDER BY USER_ID DESC;


SELECT * FROM SY_INSPCT_INSTT_USER
ORDER BY INSPCT_INSTT_SEQNO DESC;

