SELECT * FROM RS_PCN;
SELECT * FROM RS_PCN_CHANGEPOINT;

SELECT * FROM SY_UNIT_TEST
ORDER BY UNIT_TEST_SEQNO;
SELECT * FROM RS_PCN
ORDER BY PCN_SEQNO;
SELECT * FROM RS_PCN_CHANGEPOINT
ORDER BY PCN_SEQNO;

SELECT * FROM SY_USER;

SELECT * FROM RS_PCN;

SELECT * FROM SY_SANCTN_LINE;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE LIKE '%CM%';

SELECT * FROM AT_QLITY_DOC_HIST A
LEFT JOIN RS_PCN B ON A.SEQNO = B.PCN_SEQNO
WHERE A.SEQNO = 265;

SELECT * FROM AT_QLITY_DOC_HIST A
LEFT JOIN RS_PCN B ON A.SEQNO = B.PCN_SEQNO
WHERE A.SEQNO = 273
ORDER BY A.QLITY_DOC_HIST_SEQNO;


SELECT * FROM RS_PCN
WHERE PCN_SEQNO = 273;

SELECT * FROM SY_USER;

SELECT
A.TABLE_NM,
A.TABLE_CM_NM,
A.COLUMN_NM,
A.COLUMN_CM_NM,
A.CHANGE_BFE_CN,
A.CHANGE_AFTER_CN,
B.USER_NM,
TO_CHAR(A.LAST_CHANGE_DT, 'YYYY-MM-DD') AS lastChangeDt
FROM AT_QLITY_DOC_HIST A
LEFT JOIN SY_USER B ON A.LAST_CHANGER_ID = B.USER_ID
WHERE SEQNO = 275
AND A.TABLE_NM = 'RS_PCN'
ORDER BY A.QLITY_DOC_HIST_SEQNO;

SELECT * FROM RS_PCN
ORDER BY PCN_SEQNO DESC;

DELETE FROM RS_PCN
WHERE PCN_SEQNO = 274;

COMMIT;




