SELECT * FROM RS_PCN;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'RS24'
ORDER BY CMMN_CODE;

SELECT * FROM RS_PCN
ORDER BY PCN_SEQNO;

SELECT * FROM RS_PCN;
SELECT * FROM RS_PCN_CHANGEPOINT
ORDER BY PCN_CHANGEPOINT_SEQNO;


SELECT * FROM SY_UNIT_TEST;
SELECT * FROM SY_MENU_ACCTO_CHARGER;
SELECT * FROM SY_MENU;

SELECT * FROM SY_MENU A
LEFT JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY A.MENU_SEQNO;






