SELECT PKG_CRYPTO.ENCRYPT(1111) FROM DUAL;

SELECT PASSWORD FROM SY_USER WHERE USER_NM = '包府磊1';

SELECT PASSWORD FROM SY_USER
WHERE USER_NM = '包府磊1';

SELECT * FROM SY_USER;

UPDATE SY_USER SET
PASSWORD_FAILR_CO = 0;


SELECT * FROM SY_SYS_MANAGE;

COMMIT;

SELECT * FROM SY_USER;


UPDATE SY_USER SET
PASSWORD = (SELECT PKG_CRYPTO.ENCRYPT(1231) FROM DUAL)
WHERE USER_ID = 1;

SELECT * FROM SY_AUTHOR_USER;


SELECT * FROM SY_INSPCT_INSTT
ORDER BY INSPCT_INSTT_SEQNO DESC;

DELETE FROM SY_INSPCT_INSTT
WHERE INSPCT_INSTT_SEQNO = 468;

SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_MENU;
SELECT * FROM SY_AUTHOR_USER;

SELECT * FROM SY_USER;

SELECT * FROM SY_USER;
SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_INSPCT_INSTT_USER A
LEFT JOIN SY_USER B ON A.USER_ID = B.USER_ID
LEFT JOIN SY_INSPCT_INSTT C ON A.INSPCT_INSTT_SEQNO = C.INSPCT_INSTT_SEQNO
LEFT JOIN SY_AUTHOR_USER D ON A.USER_ID = D.USER_ID;


SELECT * FROM SY_AUTHOR_USER;

SELECT * FROM SY_INSPCT_INSTT;

SELECT D.USER_ID, D.USER_NM, A.INSPCT_INSTT_NM FROM
(SELECT * FROM SY_INSPCT_INSTT
START WITH UPPER_INSPCT_INSTT_SEQNO IS NULL
CONNECT BY PRIOR INSPCT_INSTT_SEQNO = UPPER_INSPCT_INSTT_SEQNO
ORDER SIBLINGS BY INSPCT_INSTT_SEQNO ASC
) A
LEFT JOIN SY_INSPCT_INSTT_USER B ON A.INSPCT_INSTT_SEQNO = B.INSPCT_INSTT_SEQNO
LEFT JOIN SY_AUTHOR_USER C ON B.USER_ID = C.USER_ID
LEFT JOIN SY_USER D ON B.USER_ID = D.USER_ID;


SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_USER;



SELECT * FROM SY_EXCP_LOG
ORDER BY EXCP_LOG_SEQNO DESC;


SELECT * FROM SY_USER;

SELECT * FROM SY_SYS_MANAGE;


SELECT * FROM SY_CMMN_CODE;


SELECT * FROM SY_USER;


SELECT * FROM SY_USER;

SELECT * FROM SY_INSPCT_INSTT
ORDER BY INSPCT_INSTT_SEQNO DESC;

SELECT * FROM SY_INSPCT_INSTT_USER
ORDER BY INSPCT_INSTT_SEQNO DESC;


SELECT *
FROM (SELECT * FROM SY_INSPCT_INSTT
				START WITH UPPER_INSPCT_INSTT_SEQNO IS NULL
				CONNECT BY PRIOR INSPCT_INSTT_SEQNO = UPPER_INSPCT_INSTT_SEQNO
				ORDER SIBLINGS BY INSPCT_INSTT_SEQNO ASC
			) A

			INNER JOIN SY_INSPCT_INSTT_USER B ON A.INSPCT_INSTT_SEQNO = B.INSPCT_INSTT_SEQNO
			INNER JOIN SY_AUTHOR_USER C ON B.USER_ID = C.USER_ID
			INNER JOIN SY_USER D ON B.USER_ID = D.USER_ID AND C.AUTHOR_CODE = 21
		WHERE 1=1
			AND D.USE_AT = 'Y'
			AND D.DELETE_AT = 'N'
			AND C.AUTHOR_CODE IS NOT NULL
      AND B.USER_ID = 162;


SELECT * FROM SY_INSPCT_INSTT_USER
WHERE USER_ID = 162;

SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_USER;

SELECT * FROM SY_SYS_MANAGE;

SELECT * FROM SY_USER;

