
SELECT * FROM KL_EQPMN;
SELECT * FROM KL_EQPMN_CRRCT_HIST;
SELECT * FROM KL_EQPMN_REPAIR_HIST;


SELECT * FROM SY_ENTRPS;


SELECT A.PASSWORD
         , PKG_CRYPTO.ENCRYPT(A.PASSWORD) ENC_PASS
         , PKG_CRYPTO.DECRYPT(PKG_CRYPTO.ENCRYPT(A.PASSWORD)) DEC_PASS
  FROM SY_USER A;

SELECT PKG_CRYPTO.DECRYPT('6A9067693078BCAC3519526AD91C7537') FROM DUAL;

SELECT * FROM SY_ENTRPS A
LEFT JOIN (SELECT ENTRPS_SEQNO,PKG_CRYPTO.DECRYPT(IHIDNUM) IHIDNUM FROM SY_ENTRPS) B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO
WHERE B.IHIDNUM LIKE  '501227%';


SELECT * FROM IM_RCEPT_EXPR_IEM;
SELECT * FROM IM_RCEPT;


SELECT * FROM IM_RCEPT_SPLORE;

SELECT * FROM KL_PRDUCT;

SELECT * FROM IM_RCEPT_SPLORE;


SELECT * FROM IM_RCEPT_SPLORE_VIEW;
SELECT * FROM IM_RCEPT_SPLORE;

SELECT * FROM CN_PRDLST;

SELECT * FROM KL_PRDUCT;

PRDUCT_SEQNO;
SELECT
	D.PRDUCT_NM
FROM IM_RCEPT_EXPR_IEM A

LEFT JOIN IM_RCEPT B ON A.RCEPT_SEQNO = B.RCEPT_SEQNO
LEFT JOIN IM_RCEPT_SPLORE D ON A.RCEPT_SPLORE_SEQNO = D.RCEPT_SPLORE_SEQNO
LEFT JOIN IM_RCEPT_SPLORE_VIEW XD ON D.RCEPT_SPLORE_SEQNO = XD.RCEPT_SPLORE_SEQNO
LEFT JOIN IM_RCEPT_ENTRPS M ON A.RCEPT_SEQNO = M.RCEPT_SEQNO AND M.ENTRPS_SE_CODE = 'IM23000001';


SELECT A.SPLORE_PICKMAN FROM IM_RCEPT_SPLORE A;

-- 의뢰업체 명 생산자 명
SELECT * FROM IM_RCEPT_SPLORE;

SELECT * FROM KL_PRDUCT;

SELECT * FROM SY_PRINTNG;

SELECT * FROM IM_RCEPT_ENTRPS;






