SELECT * FROM SY_USER;


SELECT * FROM SY_USER;

SELECT * FROM PM_PRJCT_MENU;

UPDATE PM_PRJCT_MENU SET
DELETE_AT = 'N'
WHERE PRJCT_MENU_SEQNO = 45;

COMMIT;

SELECT * FROM PM_UNIT_TEST
ORDER BY UNIT_TEST_SEQNO DESC;


SELECT * FROM SY_BBS;

SELECT * FROM SY_BBS_ANSWER;
SELECT * FROM SY_BBS_SNTNC;

SELECT * FROM PM_UNIT_TEST
WHERE UNIT_TEST_SEQNO = 61;


SELECT * FROM PM_UNIT_TEST
ORDER BY LAST_CHANGE_DT DESC;

COMMIT;


SELECT * FROM SY_ATCHMNFL
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM SY_ATCHMNFL_DETAIL
ORDER BY LAST_CHANGE_DT DESC;


SELECT * FROM PM_UNIT_TEST
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM PM_PRJCT
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM PM_PRJCT_MENU
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM PM_PRJCT_CHARGER
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM SY_USER
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM SY_INSPCT_INSTT
ORDER BY LAST_CHANGE_DT DESC;

SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

SELECT * FROM PM_PRJCT_MENU;



