SELECT * FROM SY_USER
ORDER BY USER_ID;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM05';


SELECT
			DISTINCT B.PRJCT_SEQNO VALUE,
			B.PRJCT_NM KEY
		FROM PM_PRJCT_CHARGER A
		INNER JOIN PM_PRJCT B ON A.PRJCT_SEQNO = B.PRJCT_SEQNO

		WHERE A.DELETE_AT = 'N'
			AND A.USE_AT = 'Y'
			AND B.DELETE_AT = 'N'
			AND B.USE_AT = 'Y';



SELECT
			C.PRJCT_SEQNO
			, A.UNIT_TEST_SEQNO
			, A.PRJCT_MENU_SEQNO
			, A.TESTER_ID
			, A.OPETR_ID
			, A.RERGIST_NUMOT
			, C.PRJCT_NM
			, B.MENU_NM
			, E.USER_NM chargerNm
			, (SELECT USER_NM FROM SY_USER WHERE USER_ID = A.TESTER_ID) testerNm
			, TO_CHAR(A.TEST_DT, 'YYYY-MM-DD') testDt
			, (SELECT USER_NM FROM SY_USER WHERE USER_ID = A.OPETR_ID) opetrNm
			, TO_CHAR(A.PROCESS_DT, 'YYYY-MM-DD') processDt
			, A.PROCESS_TIME
			, A.PROGRS_SITTN_CODE
			, A.TEST_CN
			, A.PROCESS_CN
			, A.TEST_SE_CODE
			, (SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE CMMN_CODE = A.PROGRS_SITTN_CODE) progrsSittnCodeNm
			, A.ATCHMNFL_SEQNO

		FROM PM_UNIT_TEST A
		INNER JOIN PM_PRJCT_MENU B ON A.PRJCT_MENU_SEQNO = B.PRJCT_MENU_SEQNO
		INNER JOIN PM_PRJCT C ON B.PRJCT_SEQNO = C.PRJCT_SEQNO
		LEFT JOIN SY_USER D ON A.OPETR_ID = D.USER_ID
		LEFT JOIN SY_USER E ON B.CHARGER_ID = E.USER_ID

		WHERE A.DELETE_AT = 'N'
		ORDER BY A.UNIT_TEST_SEQNO;

SELECT *
FROM PM_UNIT_TEST A
INNER JOIN PM_PRJCT_MENU B ON A.PRJCT_MENU_SEQNO = B.PRJCT_MENU_SEQNO
INNER JOIN PM_PRJCT C ON B.PRJCT_SEQNO = C.PRJCT_SEQNO
LEFT JOIN SY_USER D ON A.OPETR_ID = D.USER_ID

WHERE A.DELETE_AT = 'N'
;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM04';

SELECT
	A.UNIT_TEST_SEQNO
  , C.PRJCT_NM
  , B.MENU_NM
  , (SELECT CMMN_CODE_NM FROM SY_CMMN_CODE WHERE UPPER_CMMN_CODE = 'PM03' AND CMMN_CODE = A.PROGRS_SITTN_CODE) progrsSittnCodeNm
  , D.LOGIN_ID

FROM PM_UNIT_TEST A
INNER JOIN PM_PRJCT_MENU B ON A.PRJCT_MENU_SEQNO = B.PRJCT_MENU_SEQNO
INNER JOIN PM_PRJCT C ON B.PRJCT_SEQNO = C.PRJCT_SEQNO
INNER JOIN SY_USER D ON A.TESTER_ID = D.USER_ID

WHERE A.UNIT_TEST_SEQNO = 82;



