SELECT COUNT(*) FROM SY_USER;

SELECT * FROM SY_AUTHOR;

SELECT * FROM SY_SYS_MANAGE;

SELECT RESIGNDTE, LOCK_AT, LOCK_RESN, USE_AT, LAST_CHANGER_ID, LAST_CHANGE_DT FROM SY_USER;


SELECT * FROM SY_USER;

UPDATE SY_USER SET
PASSWORD = (SELECT PKG_CRYPTO.ENCRYPT(1111) FROM DUAL)
WHERE USER_ID = 102;

COMMIT;

SELECT * FROM SY_USER
WHERE login_id = 'admin';



SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

DELETE FROM SY_USER
WHERE USER_ID IN(2025,2024);


SELECT SQ_SY_INSPCT_INSTT.NEXTVAL FROM DUAL;


SELECT * FROM SY_INSPCT_INSTT
ORDER BY INSPCT_INSTT_SEQNO DESC;



SELECT * FROM SY_USER
ORDER BY USER_ID DESC;


SELECT SQ_SY_USER.NEXTVAL FROM DUAL;


SELECT * FROM SY_MENU;


SELECT * FROM AT_LOGIN_HIST;
SELECT * FROM AT_MENU_USE_HIST;

SELECT * FROM SY_USER;

SELECT * FROM SY_USER;


SELECT * FROM SY_CMMN_CODE;


SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;


SELECT * FROM SY_USER A
LEFT JOIN SY_INSPCT_INSTT_USER B ON A.USER_ID = B.USER_ID;



SELECT * FROM SY_AUTHOR;
SELECT * FROM SY_AUTHOR_MENU;
SELECT * FROM SY_AUTHOR_USER;

-- user 테이블에 AUTHOR_SE_CODE ==> 공통코드
SELECT * FROM SY_USER;
SELECT * FROM SY_MENU;

SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;

SELECT * FROM SY_SYS_MANAGE;


-- 테이블 필요한지??
SELECT * FROM AT_MENU_USE_HIST;


SELECT * FROM SY_CMMN_CODE;


SELECT * FROM SY_INSPCT_INSTT_USER;