SELECT * FROM SY_USER
ORDER BY USER_ID DESC;

SELECT * FROM SY_BBS;
SELECT * FROM SY_BBS_ANSWER;
SELECT * FROM SY_BBS_SNTNC;


SELECT * FROM SY_INSPCT_INSTT;


SELECT * FROM SY_ENTRPS;

INSERT INTO SY_ENTRPS VALUES
(
	SQ_SY_ENTRPS.NEXTVAL
  ,'테스트업체'
  ,'Y'
  ,'N'
 	,1
  ,SYSDATE
);

COMMIT;

SELECT * FROM PM_PRJCT;

INSERT INTO PM_PRJCT VALUES
(
	SQ_PM_PRJCT.NEXTVAL
	, 52
	,	'테스트'
  , 123123
  ,1
  ,'PM01000001'
  ,'url/url'
  ,'비고'
  ,'Y'
  ,'N'
  ,1
  ,SYSDATE
);


SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'PM01';


SELECT
	A.PRJCT_SEQNO
  , A.CHRG_DEPT_SEQNO
  , A.ENTRPS_SEQNO
	, B.INSPCT_INSTT_NM
  , C.CMMN_CODE_NM
  , A.PRJCT_NM
  , A.PRJCT_ID
  , D.ENTRPS_NM
  , A.SVN_URL
  , (SELECT USER_NM FROM SY_USER WHERE USER_ID = E.CHARGER_ID) prjManagerNm
  , (SELECT COUNT(*) FROM PM_PRJCT_CHARGER WHERE PRJCT_SEQNO = 1 AND USE_AT ='Y' AND DELETE_AT = 'N') prjChargerCount
  , A.RM
  , A.USE_AT
FROM PM_PRJCT A
INNER JOIN SY_INSPCT_INSTT B ON A.CHRG_DEPT_SEQNO = B.INSPCT_INSTT_SEQNO
INNER JOIN SY_CMMN_CODE C ON A.PRJCT_SE_CODE = C.CMMN_CODE
INNER JOIN SY_ENTRPS D ON A.ENTRPS_SEQNO = D.ENTRPS_SEQNO
LEFT JOIN PM_PRJCT_CHARGER E ON A.PRJCT_SEQNO = E.PRJCT_SEQNO AND E.PRJCT_MNGR_AT ='Y'
WHERE 1=1
ORDER BY A.PRJCT_SEQNO;


SELECT * FROM PM_PRJCT;
SELECT * FROM PM_PRJCT_CHARGER;

SELECT COUNT(*) FROM PM_PRJCT_CHARGER A
WHERE A.PRJCT_SEQNO = 1
AND A.USE_AT ='Y'
AND A.DELETE_AT = 'N';

INSERT INTO PM_PRJCT_CHARGER VALUES
(
	1
  , 1
  , 'Y'
	, 'Y'
  , 'N'
  , 1
  , SYSDATE
);

COMMIT;

UPDATE PM_PRJCT_CHARGER SET
PRJCT_MNGR_AT = 'Y';


SELECT * FROM SY_INSPCT_INSTT;

SELECT
			A.PRJCT_SEQNO
			, A.CHRG_DEPT_SEQNO
			, A.ENTRPS_SEQNO
			, B.INSPCT_INSTT_NM
		  	, C.CMMN_CODE_NM
		  	, A.PRJCT_NM
		  	, A.PRJCT_ID
		  	, D.ENTRPS_NM
		  	, A.SVN_URL
		  	, (SELECT USER_NM FROM SY_USER WHERE USER_ID = E.CHARGER_ID) prjManagerNm
		  	, (SELECT COUNT(*) FROM PM_PRJCT_CHARGER WHERE PRJCT_SEQNO = A.PRJCT_SEQNO AND USE_AT ='Y' AND DELETE_AT = 'N') prjChargerCount
		  	, A.RM
		  	, A.USE_AT

		FROM PM_PRJCT A
		INNER JOIN SY_INSPCT_INSTT B ON A.CHRG_DEPT_SEQNO = B.INSPCT_INSTT_SEQNO
		INNER JOIN SY_CMMN_CODE C ON A.PRJCT_SE_CODE = C.CMMN_CODE
		INNER JOIN SY_ENTRPS D ON A.ENTRPS_SEQNO = D.ENTRPS_SEQNO
		LEFT JOIN PM_PRJCT_CHARGER E ON A.PRJCT_SEQNO = E.PRJCT_SEQNO AND E.PRJCT_MNGR_AT ='Y'

		WHERE 1=1
		AND A.USE_AT = 'Y'
		AND A.DELETE_AT = 'N'

		ORDER BY A.PRJCT_SEQNO;

SELECT * FROM SY_ENTRPS;


SELECT A.ENTRPS_SEQNO, A.ENTRPS_NM FROM SY_ENTRPS A
WHERE A.DELETE_AT = 'N' AND A.USE_AT = 'Y';


SELECT * FROM PM_PRJCT;

UPDATE PM_PRJCT SET
USE_AT = 'Y';

COMMIT;


SELECT * FROM PM_PRJCT_CHARGER;

SELECT * FROM PM_PRJCT;

UPDATE PM_PRJCT SET
DELETE_AT = 'N';


COMMIT;
ROLLBACK;

DELETE FROM PM_PRJCT
WHERE PRJCT_SEQNO = 21;

SELECT * FROM PM_PRJCT_CHARGER;


SELECT * FROM SY_USER;
SELECT * FROM PM_PRJCT_CHARGER;

SELECT A.USER_ID, A.USER_NM, A.LOGIN_ID
FROM SY_USER A
WHERE A.DELETE_AT = 'N'
AND A.USE_AT = 'Y'
AND A.USER_ID NOT IN (SELECT CHARGER_ID FROM PM_PRJCT_CHARGER WHERE PRJCT_SEQNO = 1);


SELECT * FROM PM_PRJCT;


SELECT * FROM SY_AUTHOR_USER;

DELETE FROM PM_PRJCT_CHARGER
WHERE PRJCT_SEQNO = 1 AND CHARGER_ID = 1;

UPDATE PM_PRJCT_CHARGER SET
PRJCT_MNGR_AT = 'N'
WHERE PRJCT_SEQNO = 1 AND CHARGER_ID = 1;

ROLLBACK;

SELECT * FROM PM_PRJCT_CHARGER;


INSERT INTO PM_PRJCT_CHARGER VALUES (
	1
  , 150
  , 'Y'
  , 'Y'
  , 'N'
  , 1
  , SYSDATE
);




