SELECT * FROM SY_USER;

SELECT * FROM SY_AUTHOR_MENU;

SELECT * FROM SY_MENU SA
WHERE SA.USE_AT = 'Y'
AND SA.UPPER_MENU_SEQNO IS NOT NULL;

SELECT * FROM SY_CMMN_CODE;




			SELECT MENU.MENU_SEQNO,
			   		MENU.UPPER_MENU_SEQNO,
						MENU.MENU_NM,
			    	MENU.MENU_DC,
			   		MENU.MNL_CN,
			    	(SELECT X.MENU_URL
			              FROM    SY_MENU X
			              JOIN
			              (
				              SELECT
					            DISTINCT SA.MENU_SEQNO, MIN(SA.SORT_ORDR) OVER(PARTITION BY SA.UPPER_MENU_SEQNO ORDER BY SA.UPPER_MENU_SEQNO, SA.SORT_ORDR) AS SORT_ORDR
					          FROM SY_MENU SA
					          WHERE SA.USE_AT = 'Y'
					          AND SA.UPPER_MENU_SEQNO IS NOT NULL
					          START WITH SA.MENU_SEQNO IN (
			                      SELECT MENU_SEQNO
			                         FROM SY_AUTHOR_MENU
			                        WHERE AUTHOR_CODE IN (
				                        SELECT
											A.AUTHOR_CODE
										FROM SY_AUTHOR_USER A
										WHERE A.USER_ID IN (
											SELECT TO_NUMBER(1) FROM DUAL
										)
 									)
 								)
          						CONNECT BY  SA.MENU_SEQNO = PRIOR SA.UPPER_MENU_SEQNO
 							) AA
			                   ON X.MENU_SEQNO = AA.MENU_SEQNO AND X.SORT_ORDR = AA.SORT_ORDR
			             WHERE CONNECT_BY_ISLEAF = 1 AND ROWNUM = 1
			        CONNECT BY PRIOR X.MENU_SEQNO = X.UPPER_MENU_SEQNO
			        START WITH X.UPPER_MENU_SEQNO = MENU.MENU_SEQNO)
			          AS MENU_URL,
			       (    SELECT X.MENU_SEQNO
			              FROM    SY_MENU X
			              JOIN
			              (
				              SELECT
					            DISTINCT SA.MENU_SEQNO, MIN(SA.SORT_ORDR) OVER(PARTITION BY SA.UPPER_MENU_SEQNO ORDER BY SA.UPPER_MENU_SEQNO, SA.SORT_ORDR) AS SORT_ORDR
					          FROM SY_MENU SA
					          WHERE SA.USE_AT = 'Y'
					          AND SA.UPPER_MENU_SEQNO IS NOT NULL
					          START WITH SA.MENU_SEQNO IN (
			                      SELECT MENU_SEQNO
			                         FROM SY_AUTHOR_MENU
			                        WHERE AUTHOR_CODE IN (
				                        SELECT
											A.AUTHOR_CODE
										FROM SY_AUTHOR_USER A
										WHERE A.USER_ID IN (
											SELECT TO_NUMBER(1) FROM DUAL
										)
 									)
 								)
          						CONNECT BY  SA.MENU_SEQNO = PRIOR SA.UPPER_MENU_SEQNO
 							) AA
			                   ON X.MENU_SEQNO = AA.MENU_SEQNO AND X.SORT_ORDR = AA.SORT_ORDR
			             WHERE CONNECT_BY_ISLEAF = 1 AND ROWNUM = 1
			        CONNECT BY PRIOR X.MENU_SEQNO = X.UPPER_MENU_SEQNO
			        START WITH X.UPPER_MENU_SEQNO = MENU.MENU_SEQNO)
			          AS MENU_CHILD_SEQNO,
			       MENU.SORT_ORDR,
			       MENU.USE_AT,
			       MENU.LAST_CHANGER_ID,
			       MENU.LAST_CHANGE_DT
			  FROM SY_MENU MENU
			  RIGHT OUTER JOIN
			  (
				  SELECT
				  SA.MENU_SEQNO
		          FROM SY_MENU SA
		          WHERE SA.USE_AT = 'Y'
		          AND SA.UPPER_MENU_SEQNO IS NOT NULL
		          START WITH SA.MENU_SEQNO IN (
				       	SELECT MENU_SEQNO
			            FROM SY_AUTHOR_MENU
			            WHERE AUTHOR_CODE IN (
							SELECT
								A.AUTHOR_CODE
							FROM SY_AUTHOR_USER A
							WHERE A.USER_ID IN (
								SELECT TO_NUMBER(1) FROM DUAL
							)
			            )
					)
          		CONNECT BY  SA.MENU_SEQNO = PRIOR SA.UPPER_MENU_SEQNO
	            GROUP BY MENU_SEQNO
			 ) AUTHOR_MENU ON MENU.MENU_SEQNO = AUTHOR_MENU.MENU_SEQNO
			 WHERE UPPER_MENU_SEQNO in ('1000')
			 ORDER BY MENU.SORT_ORDR;

SELECT * FROM SY_MENU;

SELECT * FROM SY_USER;



SELECT * FROM SY_AUTHOR_USER;
SELECT * FROM SY_AUTHOR_MENU;




		SELECT
		    MIN(A.AUTHOR_CODE) AUTHOR_CODE
			,MAX(A.STRE_AUTHOR_AT) STRE_AUTHOR_AT
			,MAX(A.INQIRE_AUTHOR_AT) INQIRE_AUTHOR_AT
			,MAX( A.DELETE_AUTHOR_AT) DELETE_AUTHOR_AT
			,MAX(OUTPT_AUTHOR_AT) OUTPT_AUTHOR_AT
		FROM SY_AUTHOR_USER A
		JOIN SY_USER B ON A.USER_ID = B.USER_ID AND B.USER_ID = 1
		JOIN (
			SELECT AUTHOR_CODE
			FROM SY_AUTHOR_MENU
			WHERE MENU_SEQNO = 1051
		) C ON A.AUTHOR_CODE = C.AUTHOR_CODE
		WHERE B.DELETE_AT = 'N';

SELECT * FROM SY_CMMN_CODE;

SELECT * FROM SY_MENU;


SELECT A.* FROM SY_USER A;

SELECT A.BEST_INSPCT_INSTT_SEQNO FROM SY_INSPCT_INSTT A;
SELECT * FROM SY_INSPCT_INSTT_USER;


-- 사용자 머지문
MERGE INTO SY_INSPCT_INSTT
USING DUAL
ON (GW_ORGNZT_INTRFC_KEY = 1)
WHEN MATCHED THEN
	UPDATE SET
	INSPCT_INSTT_SEQNO = 1,
  BEST_INSPCT_INSTT_SEQNO = 1,
  UPPER_INSPCT_INSTT_SEQNO = 1,
  INSPCT_INSTT_NM = '1',
	LAST_CHANGER_ID = 1,
	LAST_CHANGE_DT = SYSDATE
WHEN NOT MATCHED THEN
	INSERT (INSPCT_INSTT_SEQNO, BEST_INSPCT_INSTT_SEQNO, UPPER_INSPCT_INSTT_SEQNO, INSPCT_INSTT_NM, LAST_CHANGER_ID, LAST_CHANGE_DT)
  VALUES (1,1,1,1,1,SYSDATE);



SELECT * FROM SY_INSPCT_INSTT;
SELECT * FROM SY_INSPCT_INSTT_USER;



