/* */
SELECT * FROM RS_PCN;
SELECT * FROM RS_PCN_CHANGEPOINT;


SELECT * FROM SY_MENU;

SELECT A.MENU_SEQNO, A.MENU_NM, B.CHARGER_NM FROM SY_MENU A
LEFT JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY MENU_SEQNO;

SELECT * FROM SY_UNIT;

SELECT * FROM SY_UNIT_TEST;
SELECT * FROM SY_MENU_ACCTO_CHARGER;

MERGE
INTO SY_MENU A
USING (SELECT * FROM SY_MENU_ACCTO_CHARGER
				WHERE MENU_SEQNO = 19
) B
ON A.MENU_SEQNO = B.MENU_SEQNO AND B.CHARGER_NM IN NULL
WHEN MATCHED THEN
	INSERT INTO SY_MENU_ACCTO_CHARGER (B.MENU_SEQNO, B.CHARGER_NM)
  VALUES (19,'包府磊')
WHEN NOT MATCHED THEN
	UPDATE SET
  B.CHARGER_NM = '包府磊';

SELECT * FROM SY_MENU_ACCTO_CHARGER
WHERE MENU_SEQNO = 19;


MERGE INTO (SELECT * FROM SY_MENU_ACCTO_CHARGER
  			WHERE CHARGER_NM IS NOT NULL
        AND MENU_SEQNO = 22
				) A
USING SY_MENU B
ON (A.MENU_SEQNO = B.MENU_SEQNO)
WHERE MATCHED THEN
	UPDATE SET
  A.CHARGER_NM = '包府磊',
  A.MENU_SEQNO = 22
  WHERE A.MENU_SEQNO = 22
WHERE NOT MATCHED THEN
	INSERT (A.MENU_SEQNO, A.CHARGER_NM)
  VALUES (22, '包府磊');

SELECT * FROM SY_MENU;
SELECT * FROM SY_MENU_ACCTO_CHARGER
WHERE CHARGER_NM IS NOT NULL
AND MENU_SEQNO = 22;
INSERT INTO SY_MENU_ACCTO_CHARGER (MENU_SEQNO, CHARGER_NM)
VALUES (19, '包府磊');


COMMIT;


INSERT INTO SY_MENU_ACCTO_CHARGER
VALUES (49, '绝澜');

SELECT * FROM SY_MENU_ACCTO_CHARGER;

DELETE FROM SY_MENU_ACCTO_CHARGER
WHERE CHARGER_NM = '绝澜';

SELECT A.MENU_SEQNO, A.MENU_NM, B.CHARGER_NM FROM SY_MENU A
LEFT JOIN SY_MENU_ACCTO_CHARGER B ON A.MENU_SEQNO = B.MENU_SEQNO
ORDER BY MENU_SEQNO ASC;


MERGE INTO (SELECT * FROM SY_MENU_ACCTO_CHARGER WHERE MENU_SEQNO = 22) A
USING SY_MENU B
ON (A.MENU_SEQNO = B.MENU_SEQNO)
WHEN MATCHED THEN
	UPDATE SET CHARGER_NM = '包府'
WHEN NOT MATCHED THEN
	INSERT (A.MENU_SEQNO, A.CHARGER_NM)
  VALUES (22, '包府');

SELECT * FROM SY_MENU_ACCTO_CHARGER;

MERGE INTO SY_MENU_ACCTO_CHARGER
USING DUAL
ON (MENU_SEQNO = 22)
WHEN MATCHED THEN
	UPDATE SET CHARGER_NM = '包府磊'
WHEN NOT MATCHED THEN
	INSERT (MENU_SEQNO, CHARGER_NM)
  VALUES (22, '包府磊');



SELECT * FROM SY_MENU;
SELECT * FROM SY_MENU_ACCTO_CHARGER;
SELECT * FROM SY_MENU_ACCTO_CHARGER WHERE MENU_SEQNO = 22;





