SELECT * FROM SY_ENTRPS;

SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC;



SELECT * FROM SY_ENTRPS A
LEFT JOIN SY_ENTRPS_SE B ON A.ENTRPS_SEQNO = B.ENTRPS_SEQNO AND B.ENTRPS_SE_CODE ='SY08000001'
LEFT JOIN SY_ENTRPS_SE C ON A.ENTRPS_SEQNO = C.ENTRPS_SEQNO AND C.ENTRPS_SE_CODE = 'SY08000002'
ORDER BY A.ENTRPS_SEQNO DESC;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'SY08';

SELECT * FROM SY_ENTRPS_SE
ORDER BY ENTRPS_SEQNO DESC;

SELECT * FROM SY_ENTRPS
ORDER BY ENTRPS_SEQNO DESC;


DELETE FROM SY_ENTRPS
WHERE ENTRPS_SEQNO = 134;


DELETE FROM SY_ENTRPS_SE
WHERE ENTRPS_SEQNO = 134;

COMMIT;

SELECT COUNT(*) FROM SY_ENTRPS WHERE ENTRPS_NM = '두산' AND ENTRPS_SEQNO != 133;

SELECT * FROM SY_ENTRPS WHERE ENTRPS_NM = '두산';

SELECT * FROM SY_UNIT WHERE UNIT_NM = '%';



SELECT * FROM SY_UNIT A
INNER JOIN SY_UNIT B ON A.UNIT_NM = B.UNIT_NM AND A.UNIT_SEQNO != B.UNIT_SEQNO;

DELETE FROM SY_UNIT WHERE UNIT_SEQNO = 29;

SELECT * FROM SY_UNIT
ORDER BY UNIT_SEQNO;

UPDATE SY_UNIT SET
DELETE_AT = 'N'
WHERE UNIT_SEQNO = 1;

COMMIT;

SELECT * FROM RS_AUDIT;

SELECT * FROM RS_PCN;

SELECT * FROM RS_PCN
WHERE PCN_NO = 'FCC-PCN-22-05-011';

SELECT * FROM RS_PCN;

SELECT * FROM SY_UNIT;
INSERT INTO SY_UNIT
VALUES
(
	SQ_SY_UNIT.NEXTVAL,
  'SY10000002',
  '%',
  'Y',
  'Y',
  1,
  SYSDATE
);

COMMIT;

SELECT * FROM SY_UNIT
WHERE DELETE_AT = 'Y';

UPDATE SY_UNIT SET
DELETE_AT = 'Y'
WHERE UNIT_NM = '테스트';

SELECT A.PCN_SEQNO, A.PCN_NM, A.CHRG_DEPT_CODE FROM RS_PCN A
ORDER BY PCN_SEQNO DESC;

SELECT * FROM RS_PCN
ORDER BY PCN_SEQNO DESC;

SELECT * FROM SY_USER;

SELECT * FROM RS_PCN A
INNER JOIN SY_USER B ON A.CHRG_DEPT_CODE = B.DEPT_CODE;