SELECT * FROM SY_ENTRPS;
SELECT * FROM SY_ENTRPS_SE;

SELECT * FROM SY_CMMN_CODE
WHERE UPPER_CMMN_CODE = 'SY08';

SELECT * FROM SY_LANG_DETAIL
WHERE NATION_LANG_CODE = 'C100000480';

SELECT * FROM SY_LANG_MASTR
WHERE LANG_CODE = 'C100000480';



